// RMF Operational Commerce design system - Solaris Ivory Theme Specification
export const designSystem = {
  colors: {
    surface: '#fbf9f8',
    'surface-dim': '#dbdad9',
    'surface-bright': '#fbf9f8',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f5f3f2',
    'surface-container': '#efedec',
    'surface-container-high': '#e9e8e7',
    'surface-container-highest': '#e4e2e1',
    'on-surface': '#1b1c1b',
    'on-surface-variant': '#5a4136',
    'inverse-surface': '#303030',
    'inverse-on-surface': '#f2f0ef',
    outline: '#8e7164',
    'outline-variant': '#e2bfb0',
    'surface-tint': '#a04100',
    primary: {
      DEFAULT: '#a04100',
      hover: '#ff6b00',
      container: '#ff6b00',
      onContainer: '#572000',
    },
    'on-primary': '#ffffff',
    'primary-container': '#ff6b00',
    'on-primary-container': '#572000',
    'inverse-primary': '#ffb693',
    secondary: {
      DEFAULT: '#5e5e5e',
      container: '#e3e2e2',
      onContainer: '#646464',
    },
    'on-secondary': '#ffffff',
    'secondary-container': '#e3e2e2',
    'on-secondary-container': '#646464',
    tertiary: {
      DEFAULT: '#6c5b4b',
      container: '#a99583',
      onContainer: '#3c2e20',
    },
    'on-tertiary': '#ffffff',
    'tertiary-container': '#a99583',
    'on-tertiary-container': '#3c2e20',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#ffdbcc',
    'primary-fixed-dim': '#ffb693',
    'on-primary-fixed': '#351000',
    'on-primary-fixed-variant': '#7a3000',
    'secondary-fixed': '#e3e2e2',
    'secondary-fixed-dim': '#c7c6c6',
    'on-secondary-fixed': '#1b1c1c',
    'on-secondary-fixed-variant': '#464747',
    'tertiary-fixed': '#f6dec9',
    'tertiary-fixed-dim': '#d9c3ae',
    'on-tertiary-fixed': '#25190c',
    'on-tertiary-fixed-variant': '#534435',
    background: '#fbf9f8',
    'on-background': '#1b1c1b',
    'surface-variant': '#e4e2e1',
  },
  typography: {
    fontFamilies: {
      sans: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      heading: ['Work Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
    },
  },
  spacing: {
    gutter: '16px',
    'container-max': '1440px',
    xl: '40px',
    lg: '24px',
    md: '16px',
    sm: '8px',
    xs: '4px',
    unit: '4px',
  },
  borderRadius: {
    DEFAULT: '0.125rem',
    sm: '0.125rem',
    md: '0.25rem',
    lg: '0.25rem',
    xl: '0.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    DEFAULT: '0 8px 30px rgba(27, 28, 28, 0.03)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -1px rgba(0, 0, 0, 0.04)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
  }
};
