export type CatalogFieldType = 'text' | 'number' | 'select' | 'multi_select' | 'boolean' | 'date' | 'color';

export type CatalogField = {
  key: string;
  label: string;
  type: CatalogFieldType;
  required?: boolean;
  unit?: string;
  options?: string[];
  min?: number;
  max?: number;
  searchable?: boolean;
  filterable?: boolean;
};

export type CatalogCategory = {
  id: string;
  label: string;
  productType: string;
  defaultUnit: string;
  aliases: string[];
  synonyms?: string[];
  searchBoost?: number;
  isActive?: boolean;
  version?: number;
  variantAxes: CatalogField[];
  attributes: CatalogField[];
  parentId?: string | null;
};

const rmfCoreCatalogCategories: CatalogCategory[] = [
  // 1. Groceries & Fresh Produce
  {
    id: 'grocery',
    label: 'Groceries & Fresh Produce',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['grocery', 'groceries', 'produce', 'fresh produce', 'food', 'dairy', 'spices', 'vegetables', 'fruit', 'meat', 'beef', 'chicken', 'fish', 'pork', 'crops', 'local food', 'harvest'],
    parentId: null,
    variantAxes: [
      { key: 'packageSize', label: 'Package size', type: 'select', options: ['250g', '500g', '1kg', '5kg', '10kg', '25kg'], filterable: true },
    ],
    attributes: [
      { key: 'originDistrict', label: 'Origin district', type: 'select', required: true, options: ['Kigali', 'Musanze', 'Rubavu', 'Huye', 'Nyagatare', 'Muhanga', 'Rwamagana', 'Other'], searchable: true, filterable: true },
      { key: 'freshnessGrade', label: 'Freshness grade', type: 'select', required: true, options: ['A', 'B', 'C'], filterable: true },
      { key: 'harvestDate', label: 'Harvest date', type: 'date' },
      { key: 'organic', label: 'Organic', type: 'boolean', filterable: true },
      { key: 'shelfLifeDays', label: 'Shelf life', type: 'number', unit: 'days', min: 0, max: 365 },
    ],
  },
  {
    id: 'grocery-produce',
    label: 'Fresh Produce',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['produce', 'fresh produce', 'vegetables', 'fruits'],
    parentId: 'grocery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-produce-vegetables',
    label: 'Leafy Greens, Cabbage, Spinach, Sukuma Wiki',
    productType: 'fresh_food',
    defaultUnit: 'bundle',
    aliases: ['leafy greens', 'cabbage', 'spinach', 'sukuma wiki', 'greens', 'dodo'],
    parentId: 'grocery-produce',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-produce-roots',
    label: 'Cassava, Irish Potatoes, Sweet Potatoes, Yams, Carrots',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['cassava', 'potatoes', 'sweet potatoes', 'yams', 'carrots', 'irish potatoes', 'tubers', 'roots'],
    parentId: 'grocery-produce',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-produce-fruits',
    label: 'Avocados, Bananas, Mangoes, Passions, Pineapples',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['avocados', 'bananas', 'mangoes', 'passions', 'pineapples', 'fruits', 'passion fruit'],
    parentId: 'grocery-produce',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-produce-alliums',
    label: 'Onions, Garlic, Ginger, Fresh Chillies',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['onions', 'garlic', 'ginger', 'chillies', 'alliums', 'chili', 'spices'],
    parentId: 'grocery-produce',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins',
    label: 'Meat, Poultry & Seafood',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['meat', 'poultry', 'seafood', 'beef', 'chicken', 'fish', 'pork', 'eggs'],
    parentId: 'grocery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins-beef',
    label: 'Fresh Beef Cuts, Minced Meat, Goat Meat, Pork',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['beef', 'minced meat', 'goat meat', 'pork', 'red meat', 'meat cuts'],
    parentId: 'grocery-proteins',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins-poultry',
    label: 'Local Whole Chicken, Broilers, Turkey',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['chicken', 'broilers', 'turkey', 'poultry', 'whole chicken'],
    parentId: 'grocery-proteins',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins-eggs',
    label: 'Local & Exotic Chicken Eggs',
    productType: 'fresh_food',
    defaultUnit: 'pcs/crate',
    aliases: ['eggs', 'chicken eggs', 'egg', 'crate of eggs'],
    parentId: 'grocery-proteins',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins-fish',
    label: 'Lake Kivu Tilapia, Sambaza, Nile Perch',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['fish', 'tilapia', 'sambaza', 'nile perch', 'kivu fish'],
    parentId: 'grocery-proteins',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-proteins-processed',
    label: 'Sausages, Salami, Smokies, Bacon',
    productType: 'fresh_food',
    defaultUnit: 'pack',
    aliases: ['sausages', 'salami', 'smokies', 'bacon', 'processed meat'],
    parentId: 'grocery-proteins',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-dry',
    label: 'Grains & Dry Pulses',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['grains', 'pulses', 'beans', 'rice', 'maize', 'wheat'],
    parentId: 'grocery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-dry-beans',
    label: 'Local Beans, Yellow Beans, Peas, Lentils, Groundnuts',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['beans', 'yellow beans', 'peas', 'lentils', 'groundnuts', 'pulses', 'nuts'],
    parentId: 'grocery-dry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-dry-maize',
    label: 'Maize Flour, Premium Rice, Cassava Flour, Sorghum',
    productType: 'fresh_food',
    defaultUnit: 'kg',
    aliases: ['maize flour', 'rice', 'cassava flour', 'sorghum', 'posho', 'kawunga'],
    parentId: 'grocery-dry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-dry-wheat',
    label: 'Wheat Flour, Pasta, Spaghetti, Macaroni',
    productType: 'fresh_food',
    defaultUnit: 'pack',
    aliases: ['wheat flour', 'pasta', 'spaghetti', 'macaroni', 'flour'],
    parentId: 'grocery-dry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-pantry',
    label: 'Packaged Staples & Baking',
    productType: 'fresh_food',
    defaultUnit: 'pcs',
    aliases: ['pantry', 'staples', 'baking', 'cooking oil', 'honey', 'spices'],
    parentId: 'grocery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-pantry-cooking',
    label: 'Cooking Oils, Vegetable Fats, Ghee, Salt, Sugar',
    productType: 'fresh_food',
    defaultUnit: 'pcs',
    aliases: ['cooking oil', 'vegetable fat', 'ghee', 'salt', 'sugar', 'cooking fats'],
    parentId: 'grocery-pantry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-pantry-spreads',
    label: 'Honey, Fruit Jams, Peanut Butter, Margarine',
    productType: 'fresh_food',
    defaultUnit: 'pcs',
    aliases: ['honey', 'jam', 'peanut butter', 'margarine', 'spreads'],
    parentId: 'grocery-pantry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-pantry-spices',
    label: 'Baking Powder, Yeast, Black Pepper, Curry Powder, Bouillon Cubes',
    productType: 'fresh_food',
    defaultUnit: 'pcs',
    aliases: ['baking powder', 'yeast', 'black pepper', 'curry powder', 'bouillon', 'spices', 'royco'],
    parentId: 'grocery-pantry',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-beverages',
    label: 'Drinks & Liquid Refreshments',
    productType: 'fresh_food',
    defaultUnit: 'bottle',
    aliases: ['drinks', 'beverages', 'water', 'juice', 'soda', 'beer', 'wine', 'milk'],
    parentId: 'grocery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-beverages-soft',
    label: 'Mineral Water, Juices, Sodas, Energy Drinks',
    productType: 'fresh_food',
    defaultUnit: 'bottle',
    aliases: ['water', 'juices', 'sodas', 'energy drinks', 'soft drinks'],
    parentId: 'grocery-beverages',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-beverages-alcoholic',
    label: 'Commercial Beers, Local Brews, Wines, Spirits',
    productType: 'fresh_food',
    defaultUnit: 'bottle',
    aliases: ['beer', 'local brews', 'wines', 'spirits', 'alcohol', 'liquor'],
    parentId: 'grocery-beverages',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'grocery-beverages-dairy',
    label: 'Fresh Milk, UHT Long-Life Milk, Yogurt, Cheese',
    productType: 'fresh_food',
    defaultUnit: 'packet',
    aliases: ['milk', 'uht milk', 'yogurt', 'cheese', 'dairy', 'inange'],
    parentId: 'grocery-beverages',
    variantAxes: [],
    attributes: [],
  },

  // 2. Fashion & Apparel
  {
    id: 'fashion',
    label: 'Fashion & Apparel',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['fashion', 'apparel', 'clothing', 'clothes', 'textiles', 'kitenge', 'fabric', 'streetwear', 'hoodies', 't-shirts', 'local brands'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Size', type: 'select', options: ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'Custom'], filterable: true },
      { key: 'color', label: 'Color', type: 'color', filterable: true },
    ],
    attributes: [
      { key: 'material', label: 'Material', type: 'select', required: true, options: ['Cotton', 'Kitenge', 'Silk', 'Wool', 'Polyester', 'Leather', 'Mixed'], searchable: true, filterable: true },
      { key: 'gender', label: 'Fit for', type: 'select', options: ['Women', 'Men', 'Kids', 'Unisex'], filterable: true },
      { key: 'fit', label: 'Fit', type: 'select', options: ['Slim', 'Regular', 'Relaxed', 'Custom'], filterable: true },
      { key: 'lengthMeters', label: 'Fabric length', type: 'number', unit: 'm', min: 0 },
      { key: 'care', label: 'Care instructions', type: 'text' },
    ],
  },
  {
    id: 'fashion-clothing',
    label: 'Clothing & Garments',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['clothing', 'garments', 'clothes'],
    parentId: 'fashion',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-clothing-streetwear',
    label: 'Hoodies, Sweatshirts, Graphic Tees, Denim Jeans',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['hoodies', 'sweatshirts', 'graphic tees', 'denim', 'jeans', 'streetwear', 't-shirts'],
    parentId: 'fashion-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-clothing-traditional',
    label: 'Kitenge Outfits, Umushanana, Custom Tailored Wear',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['kitenge outfits', 'umushanana', 'traditional wear', 'tailored wear', 'mushanana'],
    parentId: 'fashion-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-clothing-casual',
    label: 'Everyday Shirts, Trousers, Skirts, Summer Dresses',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['shirts', 'trousers', 'skirts', 'summer dresses', 'casual wear', 'dresses'],
    parentId: 'fashion-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-clothing-formal',
    label: 'Suits, Blazers, Office Shirts, Official Dresses',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['suits', 'blazers', 'office shirts', 'official dresses', 'formal wear'],
    parentId: 'fashion-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-clothing-innerwear',
    label: 'Underwear, Socks, Vests, Sleepwear',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['underwear', 'socks', 'vests', 'sleepwear', 'innerwear'],
    parentId: 'fashion-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-accessories',
    label: 'Bags & Accessories',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['bags', 'accessories', 'wallets', 'jewelry', 'eyewear', 'headwear'],
    parentId: 'fashion',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-accessories-bags',
    label: 'Handcrafted Bags, Backpacks, Leather Wallets, Purses',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['handcrafted bags', 'backpacks', 'wallets', 'purses', 'bags', 'leather bags'],
    parentId: 'fashion-accessories',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-accessories-jewelry',
    label: 'Artisan Beadwork, Necklaces, Rings, Bracelets',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['beadwork', 'necklaces', 'rings', 'bracelets', 'artisan jewelry', 'jewelry'],
    parentId: 'fashion-accessories',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-accessories-eyewear',
    label: 'Sunglasses, Prescription Frames',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['sunglasses', 'prescription frames', 'eyewear', 'glasses'],
    parentId: 'fashion-accessories',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-accessories-headwear',
    label: 'Caps, Beanies, Sun Hats, Cultural Headwraps',
    productType: 'apparel',
    defaultUnit: 'pcs',
    aliases: ['caps', 'beanies', 'sun hats', 'headwraps', 'hats', 'headwear'],
    parentId: 'fashion-accessories',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-textiles',
    label: 'Fabrics & Raw Textiles',
    productType: 'apparel',
    defaultUnit: 'm',
    aliases: ['fabrics', 'textiles', 'kitenge fabric', 'cotton fabric', 'synthetic fabric'],
    parentId: 'fashion',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-textiles-kitenge',
    label: 'Premium Kitenge & Wax Fabrics',
    productType: 'apparel',
    defaultUnit: 'm',
    aliases: ['kitenge fabric', 'wax fabrics', 'kitenge', 'african wax'],
    parentId: 'fashion-textiles',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-textiles-cotton',
    label: 'Pure Cotton, Wool, Linen Fabrics',
    productType: 'apparel',
    defaultUnit: 'm',
    aliases: ['cotton fabric', 'wool fabric', 'linen fabric', 'pure cotton'],
    parentId: 'fashion-textiles',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'fashion-textiles-synthetic',
    label: 'Polyester, Satin, Nylon Materials',
    productType: 'apparel',
    defaultUnit: 'm',
    aliases: ['polyester', 'satin', 'nylon', 'synthetic fabric', 'materials'],
    parentId: 'fashion-textiles',
    variantAxes: [],
    attributes: [],
  },

  // 3. Shoes & Footwear
  {
    id: 'shoes',
    label: 'Shoes & Footwear',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['shoes', 'footwear', 'boots', 'sandals', 'sneakers', 'heels', 'slippers'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Shoe Size (EU)', type: 'select', options: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', 'Custom'], filterable: true },
      { key: 'color', label: 'Color', type: 'color', filterable: true },
    ],
    attributes: [
      { key: 'material', label: 'Material', type: 'select', required: true, options: ['Leather', 'Suede', 'Canvas', 'Rubber', 'Synthetic', 'Mixed'], searchable: true, filterable: true },
      { key: 'gender', label: 'Fit for', type: 'select', options: ['Women', 'Men', 'Kids', 'Unisex'], filterable: true },
      { key: 'shoeType', label: 'Shoe Type', type: 'select', options: ['Sneakers', 'Formal', 'Boots', 'Sandals', 'Heels', 'Loafers', 'Other'], filterable: true },
      { key: 'fastening', label: 'Fastening Type', type: 'select', options: ['Laces', 'Slip-on', 'Velcro', 'Buckle', 'Zipper'], filterable: true },
      { key: 'care', label: 'Care Instructions', type: 'text' },
    ],
  },
  {
    id: 'shoes-formal',
    label: 'Formal Footwear',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['formal footwear', 'formal shoes', 'oxfords', 'heels', 'flats'],
    parentId: 'shoes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-formal-oxfords',
    label: 'Leather Oxfords, Derbies, Loafers',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['oxfords', 'derbies', 'loafers', 'leather shoes', 'formal shoes men'],
    parentId: 'shoes-formal',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-formal-heels',
    label: 'Pumps, Stilettos, Block Heels',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['heels', 'pumps', 'stilettos', 'block heels', 'formal heels'],
    parentId: 'shoes-formal',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-formal-flats',
    label: 'Ballet Flats, Pointed Dress Flats',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['flats', 'ballet flats', 'pointed flats', 'dress flats'],
    parentId: 'shoes-formal',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-casual',
    label: 'Casual & Daily Footwear',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['casual shoes', 'sneakers', 'sandals', 'slippers'],
    parentId: 'shoes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-casual-sneakers',
    label: 'Street Sneakers, Lifestyle Kicks, Canvas Slip-ons',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['sneakers', 'street sneakers', 'lifestyle kicks', 'canvas slip-ons', 'kicks'],
    parentId: 'shoes-casual',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-casual-sandals',
    label: 'Custom Made Leather Sandals, Open Shoes, Slippers',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['sandals', 'leather sandals', 'open shoes', 'slippers', 'custom sandals'],
    parentId: 'shoes-casual',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-boots',
    label: 'Boots',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['boots', 'leather boots', 'ankle boots'],
    parentId: 'shoes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'shoes-boots-leather',
    label: 'Leather Ankle Boots, Chelseas, Combat Boots',
    productType: 'footwear',
    defaultUnit: 'pair',
    aliases: ['leather boots', 'ankle boots', 'chelsea boots', 'combat boots'],
    parentId: 'shoes-boots',
    variantAxes: [],
    attributes: [],
  },

  // 4. Sportswear, Fitness & Outdoor
  {
    id: 'sportswear',
    label: 'Sportswear & Athletic Gear',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['sportswear', 'fitness', 'athletic gear', 'activewear', 'jerseys', 'gym gear'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Size', type: 'select', options: ['S', 'M', 'L', 'XL', 'XXL', 'Custom'], filterable: true },
      { key: 'color', label: 'Color', type: 'color', filterable: true },
    ],
    attributes: [
      { key: 'brand', label: 'Brand', type: 'text', searchable: true },
      { key: 'material', label: 'Material', type: 'select', options: ['Polyester', 'Nylon', 'Spandex', 'Cotton Blend', 'Other'], filterable: true },
      { key: 'sportType', label: 'Sport', type: 'select', options: ['Running', 'Gym/Fitness', 'Football', 'Basketball', 'Yoga', 'Tennis', 'Other'], filterable: true },
    ],
  },
  {
    id: 'sportswear-clothing',
    label: 'Athletic Apparel',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['activewear', 'jerseys', 'tracksuits', 'athletic clothing'],
    parentId: 'sportswear',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-clothing-activewear',
    label: 'Gym Leggings, Sports Bras, Running Shorts, Compression Tops',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['gym leggings', 'sports bras', 'running shorts', 'compression tops', 'activewear'],
    parentId: 'sportswear-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-clothing-jerseys',
    label: 'Football Jerseys, Basketball Uniforms, Club Kits',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['football jerseys', 'jerseys', 'basketball uniforms', 'club kits', 'kits'],
    parentId: 'sportswear-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-clothing-tracksuits',
    label: 'Athletic Tracksuits, Warm-up Jackets',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['tracksuits', 'warm-up jackets', 'athletic tracksuits'],
    parentId: 'sportswear-clothing',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-footwear',
    label: 'Athletic Shoes',
    productType: 'sportswear',
    defaultUnit: 'pair',
    aliases: ['running shoes', 'cleats', 'football boots', 'gym shoes'],
    parentId: 'sportswear',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-footwear-running',
    label: 'Running Shoes, Cross-Trainers, Gym Sneakers',
    productType: 'sportswear',
    defaultUnit: 'pair',
    aliases: ['running shoes', 'cross-trainers', 'gym sneakers', 'running sneakers'],
    parentId: 'sportswear-footwear',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-footwear-cleats',
    label: 'Football Boots/Cleats, Rugby Shoes',
    productType: 'sportswear',
    defaultUnit: 'pair',
    aliases: ['football boots', 'cleats', 'rugby shoes', 'football cleats'],
    parentId: 'sportswear-footwear',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-equipment',
    label: 'Fitness & Training Gear',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['gym accessories', 'dumbbells', 'footballs', 'yoga mats'],
    parentId: 'sportswear',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-equipment-accessories',
    label: 'Yoga Mats, Resistance Bands, Dumbbells, Skipping Ropes',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['yoga mats', 'resistance bands', 'dumbbells', 'skipping ropes', 'fitness accessories'],
    parentId: 'sportswear-equipment',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'sportswear-equipment-sports',
    label: 'Footballs, Basketballs, Tennis Rackets, Inflators',
    productType: 'sportswear',
    defaultUnit: 'pcs',
    aliases: ['footballs', 'basketballs', 'tennis rackets', 'inflators', 'sports balls'],
    parentId: 'sportswear-equipment',
    variantAxes: [],
    attributes: [],
  },

  // 5. Bakery & Pâtisserie
  {
    id: 'bakery',
    label: 'Bakery & Confectionery',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['bakery', 'patisserie', 'confectionery', 'bread', 'cake', 'pastry', 'sweets'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Serving Size', type: 'select', options: ['Single Serving', 'Pack of 4', 'Pack of 6', 'Pack of 12', 'Small Cake (0.5kg)', 'Medium Cake (1kg)', 'Large Cake (2kg)', 'Custom'], filterable: true },
      { key: 'flavor', label: 'Flavor', type: 'select', options: ['Vanilla', 'Chocolate', 'Strawberry', 'Red Velvet', 'Banana', 'Caramel', 'Lemon', 'Fruit Blend', 'Glazed', 'Other'], filterable: true },
    ],
    attributes: [
      { key: 'dietary', label: 'Dietary Type', type: 'select', options: ['Regular', 'Vegan', 'Gluten-Free', 'Sugar-Free', 'Halal', 'Keto'], filterable: true },
      { key: 'eggless', label: 'Eggless', type: 'boolean', filterable: true },
      { key: 'shelfLifeDays', label: 'Shelf Life (Days)', type: 'number', min: 1, max: 90 },
      { key: 'allergens', label: 'Allergens Info', type: 'select', options: ['None', 'Contains Gluten', 'Contains Dairy', 'Contains Nuts', 'Contains Eggs', 'Contains Soy', 'Multiple Allergens'], filterable: true },
    ],
  },
  {
    id: 'bakery-cakes',
    label: 'Cakes & Celebrations',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['custom cakes', 'cupcakes', 'cake slices', 'celebration cakes'],
    parentId: 'bakery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-cakes-custom',
    label: 'Custom Birthday, Wedding & Fondant Cakes',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['birthday cakes', 'wedding cakes', 'fondant cakes', 'custom cakes'],
    parentId: 'bakery-cakes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-cakes-cupcakes',
    label: 'Cupcakes, Muffins',
    productType: 'bakery_good',
    defaultUnit: 'box',
    aliases: ['cupcakes', 'muffins', 'muffin', 'cupcake'],
    parentId: 'bakery-cakes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-cakes-slices',
    label: 'Sponge Cake Slices, Loaf Cakes',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['cake slices', 'sponge cake', 'loaf cakes', 'sliced cake'],
    parentId: 'bakery-cakes',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-pastries',
    label: 'Breads & Fast Snacks',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['breads', 'snacks', 'sambusa', 'mandazi', 'croissants'],
    parentId: 'bakery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-pastries-breads',
    label: 'Sourdough, Baguettes, Sliced White/Brown Loaves',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['sourdough', 'baguettes', 'sliced bread', 'bread loaves', 'white bread', 'brown bread'],
    parentId: 'bakery-pastries',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-pastries-snacks',
    label: 'Meat Sambusa, Mandazi, Chapatis, Croissants',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['sambusa', 'mandazi', 'chapatis', 'croissants', 'sambusa meat', 'fast snacks'],
    parentId: 'bakery-pastries',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-sweets',
    label: 'Desserts',
    productType: 'bakery_good',
    defaultUnit: 'box',
    aliases: ['cookies', 'donuts', 'confectionery', 'chocolates', 'sweets'],
    parentId: 'bakery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-sweets-cookies',
    label: 'Biscuits, Handcrafted Cookies, Shortbread',
    productType: 'bakery_good',
    defaultUnit: 'box',
    aliases: ['biscuits', 'cookies', 'shortbread', 'handcrafted cookies'],
    parentId: 'bakery-sweets',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-sweets-donuts',
    label: 'Glazed, Ring & Filled Donuts',
    productType: 'bakery_good',
    defaultUnit: 'pcs',
    aliases: ['donuts', 'glazed donuts', 'ring donuts', 'filled donuts'],
    parentId: 'bakery-sweets',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'bakery-sweets-confectionery',
    label: 'Local Chocolates, Candies, Sweets',
    productType: 'bakery_good',
    defaultUnit: 'pack',
    aliases: ['local chocolates', 'candies', 'sweets', 'confectionery', 'chocolate bar'],
    parentId: 'bakery-sweets',
    variantAxes: [],
    attributes: [],
  },

  // 6. Hardware & Tools (Quincaillerie)
  {
    id: 'hardware',
    label: 'Hardware & Structural Materials',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['hardware', 'tools', 'quincaillerie', 'construction', 'structural materials', 'screws', 'nails', 'paint', 'plumbing', 'electrical'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Size / Dimension', type: 'select', options: ['Small', 'Medium', 'Large', '1/2 inch', '3/4 inch', '1 inch', '2 inch', '10mm', '20mm', '50mm', '100mm', '500g', '1kg', '5kg', 'Custom'], filterable: true },
      { key: 'color', label: 'Color', type: 'color', filterable: true },
    ],
    attributes: [
      { key: 'brand', label: 'Brand', type: 'text', required: true, searchable: true, filterable: true },
      { key: 'material', label: 'Material', type: 'select', options: ['Steel', 'Iron', 'Brass', 'Copper', 'Aluminum', 'Plastic/PVC', 'Wood', 'Concrete/Cement', 'Mixed'], searchable: true, filterable: true },
      { key: 'toolType', label: 'Hardware/Tool Type', type: 'select', options: ['Hand Tool', 'Power Tool', 'Fasteners (Nails/Screws)', 'Plumbing & Fittings', 'Electrical & Wiring', 'Paint & Adhesives', 'Safety & Protective Gear', 'Building Material', 'Other'], filterable: true },
      { key: 'powerSource', label: 'Power Source', type: 'select', options: ['Manual', 'Corded Electric', 'Battery Powered', 'Pneumatic (Air)', 'Gasoline', 'N/A'], filterable: true },
      { key: 'warrantyMonths', label: 'Warranty (Months)', type: 'number', min: 0, max: 120 },
    ],
  },
  {
    id: 'hardware-construction',
    label: 'Construction & Structural',
    productType: 'hardware_tool',
    defaultUnit: 'bag',
    aliases: ['cement', 'paint', 'metals', 'rebar', 'fixtures', 'hinges'],
    parentId: 'hardware',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-construction-cement',
    label: 'Cement Bags, Sand, Gypsum Plaster, Lime',
    productType: 'hardware_tool',
    defaultUnit: 'bag',
    aliases: ['cement', 'cement bags', 'sand', 'gypsum plaster', 'lime', 'structural materials'],
    parentId: 'hardware-construction',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-construction-paint',
    label: 'Wall Paints, Undercoats, Primers, Sealants',
    productType: 'hardware_tool',
    defaultUnit: 'bucket',
    aliases: ['wall paint', 'paint', 'undercoats', 'primers', 'sealants', 'paints'],
    parentId: 'hardware-construction',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-construction-metals',
    label: 'Rebar Steel, Iron Bars, Roofing Sheets, Wire Mesh',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['rebar steel', 'iron bars', 'roofing sheets', 'wire mesh', 'steel', 'metals'],
    parentId: 'hardware-construction',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-construction-fixtures',
    label: 'Door Locks, Hinges, Handles, Nails, Screws',
    productType: 'hardware_tool',
    defaultUnit: 'pack',
    aliases: ['door locks', 'hinges', 'handles', 'nails', 'screws', 'fixtures', 'fasteners'],
    parentId: 'hardware-construction',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-tools',
    label: 'Tools & Equipment',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['electric tools', 'power drills', 'manual tools', 'hammers'],
    parentId: 'hardware',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-tools-electric',
    label: 'Power Drills, Angle Grinders, Demolition Saws',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['power drills', 'drills', 'angle grinders', 'demolition saws', 'power tools', 'electric tools'],
    parentId: 'hardware-tools',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-tools-manual',
    label: 'Hammers, Screwdrivers, Spanners, Pliers, Hand Saws',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['hammers', 'screwdrivers', 'spanners', 'pliers', 'hand saws', 'manual tools'],
    parentId: 'hardware-tools',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-utility',
    label: 'Plumbing & Electrical Infrastructure',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['pipes', 'cables', 'switches', 'sockets', 'safety gear'],
    parentId: 'hardware',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-utility-pipes',
    label: 'PVC Conduit, PPR Water Pipes, Brass Valves, Taps',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['pvc conduit', 'pipes', 'water pipes', 'brass valves', 'taps', 'plumbing pipes'],
    parentId: 'hardware-utility',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-utility-cables',
    label: 'Electrical Heavy Wiring, Earth Cables',
    productType: 'hardware_tool',
    defaultUnit: 'roll',
    aliases: ['electrical wiring', 'cables', 'earth cables', 'heavy wiring', 'wiring roll'],
    parentId: 'hardware-utility',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-utility-switches',
    label: 'Wall Sockets, Circuit Breakers, Extension Strips',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['wall sockets', 'sockets', 'circuit breakers', 'extension strips', 'switches'],
    parentId: 'hardware-utility',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'hardware-utility-safety',
    label: 'Work Helmets, High-Vis Vests, Safety Gloves',
    productType: 'hardware_tool',
    defaultUnit: 'pcs',
    aliases: ['work helmets', 'helmets', 'high-vis vests', 'safety gloves', 'safety gear'],
    parentId: 'hardware-utility',
    variantAxes: [],
    attributes: [],
  },

  // 7. Handicrafts
  {
    id: 'handicrafts',
    label: 'Traditional Crafts & Fine Arts',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['handicrafts', 'crafts', 'artisan', 'traditional crafts', 'art', 'agaseke', 'imigongo', 'fine arts'],
    parentId: null,
    variantAxes: [
      { key: 'size', label: 'Size', type: 'select', options: ['Small', 'Medium', 'Large', 'Custom'], filterable: true },
      { key: 'color', label: 'Color', type: 'color', filterable: true },
    ],
    attributes: [
      { key: 'material', label: 'Material', type: 'select', required: true, options: ['Sisal', 'Clay', 'Wood', 'Cow dung', 'Banana fiber', 'Beads', 'Mixed'], searchable: true, filterable: true },
      { key: 'artisanDistrict', label: 'Artisan district', type: 'select', required: true, options: ['Kigali', 'Huye', 'Musanze', 'Rubavu', 'Muhanga', 'Nyagatare', 'Other'], filterable: true },
      { key: 'handmade', label: 'Handmade', type: 'boolean', filterable: true },
      { key: 'productionDays', label: 'Production time', type: 'number', unit: 'days', min: 0, max: 180 },
      { key: 'dimensions', label: 'Dimensions', type: 'text' },
    ],
  },
  {
    id: 'handicrafts-woven',
    label: 'Woven Arts',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['agaseke', 'woven mats', 'woven storage', 'basket weaving'],
    parentId: 'handicrafts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-woven-agaseke',
    label: 'Traditional Agaseke Peace Baskets',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['agaseke', 'peace baskets', 'traditional baskets', 'agaseke baskets'],
    parentId: 'handicrafts-woven',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-woven-mats',
    label: 'Sisal Floor Mats, Papyrus Wall Hangings',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['sisal floor mats', 'mats', 'papyrus wall hangings', 'wall hangings', 'floor mats'],
    parentId: 'handicrafts-woven',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-woven-storage',
    label: 'Woven Hampers, Laundry & Decorative Baskets',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['woven hampers', 'laundry baskets', 'decorative baskets', 'storage baskets'],
    parentId: 'handicrafts-woven',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-art',
    label: 'Visual Masterpieces',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['imigongo', 'wooden sculptures', 'fine art', 'paintings'],
    parentId: 'handicrafts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-art-imigongo',
    label: 'Imigongo Cow-Dung Geometric Wall Art Panels',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['imigongo', 'imigongo panels', 'geometric art', 'wall art panels'],
    parentId: 'handicrafts-art',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-art-wood',
    label: 'Hand-carved Wooden Sculptures, Masks, Walking Sticks',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['wooden sculptures', 'masks', 'walking sticks', 'carved wood', 'artisan wood'],
    parentId: 'handicrafts-art',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-art-paintings',
    label: 'Local Fine Art Canvas Paintings',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['canvas paintings', 'paintings', 'fine art', 'local paintings'],
    parentId: 'handicrafts-art',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-decor',
    label: 'Artisan Utility Decor',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['clay cookware', 'pottery', 'beadwork', 'utility decor'],
    parentId: 'handicrafts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-decor-pottery',
    label: 'Clay Cookware, Vases, Terracotta Pots',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['clay cookware', 'vases', 'terracotta pots', 'pottery', 'clay pots'],
    parentId: 'handicrafts-decor',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'handicrafts-decor-beadwork',
    label: 'Hand-beaded Table Coasters, Ornamental Jewelry',
    productType: 'artisan_good',
    defaultUnit: 'pcs',
    aliases: ['beaded coasters', 'coasters', 'ornamental jewelry', 'hand-beaded', 'beadwork'],
    parentId: 'handicrafts-decor',
    variantAxes: [],
    attributes: [],
  },

  // 8. Home, Furniture & Kitchen
  {
    id: 'home',
    label: 'Home & Interior Furnishings',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['home', 'interior', 'decor', 'kitchen', 'furniture', 'household', 'furnishings'],
    parentId: null,
    variantAxes: [
      { key: 'color', label: 'Color', type: 'color', filterable: true },
      { key: 'size', label: 'Size', type: 'select', options: ['Small', 'Medium', 'Large'], filterable: true },
    ],
    attributes: [
      { key: 'material', label: 'Material', type: 'select', options: ['Wood', 'Clay', 'Metal', 'Glass', 'Fabric', 'Plastic', 'Mixed'], searchable: true, filterable: true },
      { key: 'room', label: 'Room', type: 'select', options: ['Kitchen', 'Living room', 'Bedroom', 'Bathroom', 'Outdoor'], filterable: true },
      { key: 'dimensions', label: 'Dimensions', type: 'text' },
      { key: 'fragile', label: 'Fragile', type: 'boolean', filterable: true },
    ],
  },
  {
    id: 'home-furniture',
    label: 'Furniture',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['sofas', 'beds', 'wardrobes', 'desks', 'furniture'],
    parentId: 'home',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-furniture-living',
    label: 'Sofas, Sectionals, Armchairs, Coffee Tables, TV Stands',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['sofas', 'sectionals', 'armchairs', 'coffee tables', 'tv stands', 'living room furniture'],
    parentId: 'home-furniture',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-furniture-bedding',
    label: 'Beds, Mattresses, Wooden Wardrobes, Dressers',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['beds', 'mattresses', 'wardrobes', 'dressers', 'bedding furniture', 'bedroom furniture'],
    parentId: 'home-furniture',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-furniture-office',
    label: 'Office Desks, Study Tables, Ergonomic Work Chairs',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['office desks', 'study tables', 'work chairs', 'office chairs', 'office furniture'],
    parentId: 'home-furniture',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-furniture-dining',
    label: 'Dining Table Sets, Kitchen Sideboards',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['dining table', 'table sets', 'kitchen sideboards', 'dining furniture'],
    parentId: 'home-furniture',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-decor',
    label: 'Interior Design Accents',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['curtains', 'lighting', 'chandeliers', 'mirrors'],
    parentId: 'home',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-decor-textiles',
    label: 'Window Curtains, Bedding Sheets, Cushions, Rugs',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['window curtains', 'bedding sheets', 'cushions', 'rugs', 'home textiles', 'sheets'],
    parentId: 'home-decor',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-decor-lighting',
    label: 'Chandelers, Pendant Lamps, Table Lamps, LED Bulbs',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['chandeliers', 'pendant lamps', 'table lamps', 'led bulbs', 'lighting'],
    parentId: 'home-decor',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-decor-mirrors',
    label: 'Decorative Mirrors, Framed Art Frames',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['decorative mirrors', 'mirrors', 'framed art', 'art frames'],
    parentId: 'home-decor',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-kitchen',
    label: 'Kitchen Setup',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['pots', 'pans', 'spoons', 'blenders', 'kitchenware', 'kitchen appliances'],
    parentId: 'home',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-kitchen-cookware',
    label: 'Stainless Steel Pots, Non-Stick Pans, Pressure Cookers',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['pots', 'non-stick pans', 'pressure cookers', 'cookware', 'stainless steel pots'],
    parentId: 'home-kitchen',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-kitchen-utensils',
    label: 'Wooden Spoons, Bowls, Cutting Boards, Cutlery Sets',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['wooden spoons', 'bowls', 'cutting boards', 'cutlery sets', 'utensils'],
    parentId: 'home-kitchen',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'home-kitchen-appliances',
    label: 'Blenders, Kettles, Toasters, Microwaves',
    productType: 'home_good',
    defaultUnit: 'pcs',
    aliases: ['blenders', 'kettles', 'toasters', 'microwaves', 'kitchen appliances', 'appliances'],
    parentId: 'home-kitchen',
    variantAxes: [],
    attributes: [],
  },

  // 9. Electronics & Tech
  {
    id: 'electronics',
    label: 'Electronics & Smart Computing',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['electronics', 'tech', 'computing', 'phone', 'accessories', 'charger', 'device', 'computer', 'laptop', 'appliances', 'gadgets'],
    parentId: null,
    variantAxes: [
      { key: 'color', label: 'Color', type: 'color', filterable: true },
      { key: 'capacity', label: 'Capacity', type: 'select', options: ['16GB', '32GB', '64GB', '128GB', '256GB', '512GB'], filterable: true },
    ],
    attributes: [
      { key: 'brand', label: 'Brand', type: 'text', required: true, searchable: true, filterable: true },
      { key: 'model', label: 'Model', type: 'text', searchable: true },
      { key: 'condition', label: 'Condition', type: 'select', required: true, options: ['New', 'Used like new', 'Used good', 'Refurbished'], filterable: true },
      { key: 'warrantyMonths', label: 'Warranty', type: 'number', unit: 'months', min: 0, max: 60 },
    ],
  },
  {
    id: 'electronics-computers',
    label: 'Computers & Station Gear',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['laptops', 'desktops', 'monitors', 'printers', 'keyboards'],
    parentId: 'electronics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-computers-laptops',
    label: 'Business Laptops, Notebooks, MacBooks',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['laptops', 'business laptops', 'notebooks', 'macbooks'],
    parentId: 'electronics-computers',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-computers-desktops',
    label: 'Tower Desktops, Monitors, All-in-One PCs',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['desktops', 'tower desktops', 'monitors', 'all-in-one pcs'],
    parentId: 'electronics-computers',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-computers-peripherals',
    label: 'Mice, Keyboards, External Hard Drives, Printers',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['mice', 'keyboards', 'external hard drives', 'printers', 'peripherals'],
    parentId: 'electronics-computers',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-mobile',
    label: 'Mobile Ecosystem',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['smartphones', 'tablets', 'accessories', 'chargers'],
    parentId: 'electronics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-mobile-smartphones',
    label: 'Smartphones, iOS/Android Tablets',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['smartphones', 'tablets', 'android tablets', 'iphones', 'phones'],
    parentId: 'electronics-mobile',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-mobile-accessories',
    label: 'Power Banks, Charging Cables, Fast Adapters',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['power banks', 'charging cables', 'fast adapters', 'phone accessories', 'chargers'],
    parentId: 'electronics-mobile',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-power',
    label: 'Power Infrastructure',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['solar panels', 'inverters', 'stabilizers', 'ups'],
    parentId: 'electronics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-power-solar',
    label: 'Solar Panels, Charge Controllers, Solar Home Batteries',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['solar panels', 'charge controllers', 'solar batteries', 'solar home systems'],
    parentId: 'electronics-power',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-power-inverters',
    label: 'Inverters, Backup UPS, Voltage Stabilizers',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['inverters', 'backup ups', 'ups', 'voltage stabilizers', 'power backup'],
    parentId: 'electronics-power',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-entertainment',
    label: 'Audio-Visual Media',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['tvs', 'speakers', 'headphones', 'soundbars'],
    parentId: 'electronics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-entertainment-tv',
    label: 'Smart TVs, 4K Displays',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['smart tvs', 'tvs', '4k displays', 'displays', 'tv'],
    parentId: 'electronics-entertainment',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-entertainment-audio',
    label: 'Home Theatres, Bluetooth Speakers, Soundbars',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['home theatres', 'bluetooth speakers', 'speakers', 'soundbars', 'audio systems'],
    parentId: 'electronics-entertainment',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-entertainment-headphones',
    label: 'Over-Ear Headphones, Wireless Earbuds',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['headphones', 'wireless earbuds', 'earbuds', 'over-ear headphones'],
    parentId: 'electronics-entertainment',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-networking',
    label: 'Connectivity',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['routers', 'modems', 'switches', 'wifi'],
    parentId: 'electronics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'electronics-networking-routers',
    label: 'Wi-Fi Routers, 4G/5G Modems, LAN Switches',
    productType: 'electronics',
    defaultUnit: 'pcs',
    aliases: ['routers', 'wifi routers', 'modems', 'lan switches', 'networking gear'],
    parentId: 'electronics-networking',
    variantAxes: [],
    attributes: [],
  },

  // 10. Cosmetics, Beauty & Health
  {
    id: 'cosmetics',
    label: 'Cosmetics, Personal Care & Wellness',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['cosmetics', 'beauty', 'wellness', 'infant care', 'hair care', 'makeup', 'hygiene'],
    parentId: null,
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-babies',
    label: 'Infant Care',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['baby care', 'infant care', 'baby skincare', 'baby food', 'diapers'],
    parentId: 'cosmetics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-baby-skincare',
    label: 'Gentle Baby Lotions, Oils, Antiseptic Zinc Creams',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['baby lotions', 'baby oils', 'zinc creams', 'baby skincare', 'lotions'],
    parentId: 'cosmetics-babies',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-baby-food',
    label: 'Baby Formula, Cereal Powders',
    productType: 'health_and_beauty',
    defaultUnit: 'box',
    aliases: ['baby formula', 'cereal powders', 'baby food', 'cereal', 'cerelac'],
    parentId: 'cosmetics-babies',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-baby-diapers',
    label: 'Premium Diapers, Wet Wipes',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['diapers', 'wet wipes', 'baby diapers', 'wipes'],
    parentId: 'cosmetics-babies',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hair',
    label: 'Hair Care Ecosystem',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['shampoo', 'hair braids', 'hair extensions', 'hair tools'],
    parentId: 'cosmetics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hair-shampoo',
    label: 'Local/Imported Shampoos, Deep Conditioners, Hair Oils',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['shampoos', 'conditioners', 'hair oils', 'hair shampoo', 'deep conditioners'],
    parentId: 'cosmetics-hair',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hair-braids',
    label: 'Synthetic Hair Braids, Hair Extensions, Weaves',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['hair braids', 'braids', 'hair extensions', 'weaves', 'synthetic braids'],
    parentId: 'cosmetics-hair',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hair-tools',
    label: 'Blowdryers, Straightening Irons, Hair Clippers',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['blowdryers', 'straightening irons', 'hair clippers', 'clippers', 'hair tools'],
    parentId: 'cosmetics-hair',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-makeup',
    label: 'Glamour & Fragrance',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['face powders', 'lipsticks', 'perfumes', 'colognes', 'makeup'],
    parentId: 'cosmetics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-makeup-face',
    label: 'Setting Powders, Liquid Foundations, Lipsticks, Eyeliners',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['setting powders', 'liquid foundations', 'lipsticks', 'eyeliners', 'face makeup', 'makeup'],
    parentId: 'cosmetics-makeup',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-makeup-perfumes',
    label: 'Designer Perfumes, Colognes, Fragrance Mists',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['perfumes', 'colognes', 'fragrance mists', 'designer perfumes', 'scents'],
    parentId: 'cosmetics-makeup',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hygiene',
    label: 'Daily Essentials',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['toothbrushes', 'soaps', 'razors', 'sanitary pads'],
    parentId: 'cosmetics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hygiene-dental',
    label: 'Toothbrushes, Flouride Toothpaste, Mouthwash',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['toothbrushes', 'toothpaste', 'mouthwash', 'dental care', 'flouride toothpaste'],
    parentId: 'cosmetics-hygiene',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hygiene-sanitary',
    label: 'Medicated Soaps, Body Wash, Sanitary Pads, Tampons',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['medicated soaps', 'body wash', 'sanitary pads', 'tampons', 'hygiene soaps'],
    parentId: 'cosmetics-hygiene',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-hygiene-shaving',
    label: 'Disposable Razors, Shaving Foams, Deodorants',
    productType: 'health_and_beauty',
    defaultUnit: 'pcs',
    aliases: ['razors', 'shaving foams', 'deodorants', 'shaving gear', 'disposable razors'],
    parentId: 'cosmetics-hygiene',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-wellness',
    label: 'Health Station',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['supplements', 'vitamins', 'bandages', 'antiseptics'],
    parentId: 'cosmetics',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-wellness-supplements',
    label: 'Daily Vitamins, Omega-3 Oils, Zinc/Iron Supplements',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['daily vitamins', 'vitamins', 'omega-3', 'zinc supplements', 'iron supplements', 'supplements'],
    parentId: 'cosmetics-wellness',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'cosmetics-wellness-medical',
    label: 'First Aid Bandages, Surgical Spirit, Antiseptics',
    productType: 'health_and_beauty',
    defaultUnit: 'pack',
    aliases: ['bandages', 'surgical spirit', 'antiseptics', 'first aid', 'medical supplies'],
    parentId: 'cosmetics-wellness',
    variantAxes: [],
    attributes: [],
  },

  // 11. Automotive, Moto & Transport
  {
    id: 'automotive',
    label: 'Automotive, Moto & Transport',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['automotive', 'moto', 'transport', 'spares', 'parts', 'tyres', 'car accessories'],
    parentId: null,
    variantAxes: [
      { key: 'brand', label: 'Brand', type: 'text', searchable: true },
    ],
    attributes: [
      { key: 'condition', label: 'Condition', type: 'select', options: ['New', 'Used like new', 'Used good'], filterable: true },
    ],
  },
  {
    id: 'automotive-parts',
    label: 'Mechanical Components',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['filters', 'fluids', 'electrical parts', 'engine oil'],
    parentId: 'automotive',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-parts-filters',
    label: 'Oil Filters, Air Filters, Brake Pads, Spark Plugs',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['oil filters', 'air filters', 'brake pads', 'spark plugs', 'filters', 'spares'],
    parentId: 'automotive-parts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-parts-fluids',
    label: 'Engine Oils, Radiator Coolants, Brake Fluids',
    productType: 'automotive',
    defaultUnit: 'bottle',
    aliases: ['engine oils', 'radiator coolants', 'brake fluids', 'fluids', 'motor oil'],
    parentId: 'automotive-parts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-parts-electrical',
    label: 'Maintenance-Free Car Batteries, Moto Batteries, Bulbs',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['car batteries', 'moto batteries', 'bulbs', 'electrical parts', 'batteries'],
    parentId: 'automotive-parts',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-tyres',
    label: 'Tires & Traction',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['car tyres', 'moto tyres', 'inner tubes', 'tyres'],
    parentId: 'automotive',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-tyres-car',
    label: 'Passenger Car Tyres, Heavy SUV Tyres',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['car tyres', 'suv tyres', 'passenger tyres', 'car tires'],
    parentId: 'automotive-tyres',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-tyres-moto',
    label: 'Motorcycle Tires, Bicycle Tires, Inner Tubes',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['motorcycle tires', 'bicycle tires', 'inner tubes', 'moto tires', 'moto tyres'],
    parentId: 'automotive-tyres',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-accessories',
    label: 'Maintenance Equipment',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['seat covers', 'car mats', 'car shampoo', 'microfiber'],
    parentId: 'automotive',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-accessories-interior',
    label: 'Seat Covers, Steering Grips, Rubber Car Mats',
    productType: 'automotive',
    defaultUnit: 'pcs',
    aliases: ['seat covers', 'steering grips', 'car mats', 'rubber car mats', 'interior accessories'],
    parentId: 'automotive-accessories',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'automotive-accessories-cleaning',
    label: 'Car Shampoos, Dashboard Waxes, Microfiber Cloths',
    productType: 'automotive',
    defaultUnit: 'pack',
    aliases: ['car shampoos', 'dashboard waxes', 'microfiber cloths', 'cleaning accessories'],
    parentId: 'automotive-accessories',
    variantAxes: [],
    attributes: [],
  },

  // 12. Stationery, Books & Toys
  {
    id: 'education',
    label: 'Stationery, Books & Toys',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['stationery', 'books', 'toys', 'notebooks', 'textbooks', 'games'],
    parentId: null,
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-stationery',
    label: 'Office & Student Gear',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['notebooks', 'writing paper', 'pens', 'math sets'],
    parentId: 'education',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-stationery-writing',
    label: 'Exercise Notebooks, Ballpoint Pens, Mathematical Sets',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['exercise notebooks', 'notebooks', 'pens', 'mathematical sets', 'math sets', 'writing gear'],
    parentId: 'education-stationery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-stationery-paper',
    label: 'A4 Copy Paper Reams, Manila Papers, Files',
    productType: 'education',
    defaultUnit: 'ream',
    aliases: ['a4 paper', 'copy paper', 'manila papers', 'files', 'paper reams'],
    parentId: 'education-stationery',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-books',
    label: 'Reading Materials',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['textbooks', 'novels', 'biographies', 'literature'],
    parentId: 'education',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-books-textbooks',
    label: 'School Curriculum Textbooks, Revision Guides',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['textbooks', 'school books', 'revision guides', 'curriculum books'],
    parentId: 'education-books',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-books-literature',
    label: 'Novels, African Literature Books, Biographies',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['novels', 'literature', 'african literature', 'biographies', 'storybooks'],
    parentId: 'education-books',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-toys',
    label: 'Recreation',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['dolls', 'puzzles', 'board games', 'toys', 'chess'],
    parentId: 'education',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-toys-children',
    label: 'Dolls, Building Blocks, Educational Puzzle Kits',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['dolls', 'building blocks', 'puzzle kits', 'educational toys', 'children toys'],
    parentId: 'education-toys',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'education-toys-games',
    label: 'Chess Sets, Local Board Games, Playing Cards',
    productType: 'education',
    defaultUnit: 'pcs',
    aliases: ['chess sets', 'board games', 'playing cards', 'local games', 'games'],
    parentId: 'education-toys',
    variantAxes: [],
    attributes: [],
  },

  // 13. General / Other
  {
    id: 'other',
    label: 'General / Other',
    productType: 'other',
    defaultUnit: 'pcs',
    aliases: ['other', 'general', 'misc', 'services', 'custom'],
    parentId: null,
    variantAxes: [],
    attributes: [
      { key: 'brand', label: 'Brand / maker', type: 'text', searchable: true },
      { key: 'originDistrict', label: 'Origin district', type: 'text', filterable: true },
      { key: 'condition', label: 'Condition', type: 'select', options: ['New', 'Used like new', 'Used good', 'Made to order'], filterable: true },
    ],
  },
  {
    id: 'other-services',
    label: 'Professional Tasks',
    productType: 'other',
    defaultUnit: 'pcs',
    aliases: ['tailoring', 'delivery', 'printing', 'services'],
    parentId: 'other',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'other-services-tailoring',
    label: 'Garment Alteration Jobs, Custom Tailoring Works',
    productType: 'other',
    defaultUnit: 'job',
    aliases: ['tailoring', 'garment alteration', 'tailor jobs', 'custom tailoring'],
    parentId: 'other-services',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'other-services-delivery',
    label: 'Express Moto Courier, Heavy Freight Movement',
    productType: 'other',
    defaultUnit: 'trip',
    aliases: ['delivery', 'moto courier', 'freight movement', 'express courier', 'courier'],
    parentId: 'other-services',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'other-services-printing',
    label: 'Document Printing, Photocopying, Large Format Banners',
    productType: 'other',
    defaultUnit: 'page',
    aliases: ['printing', 'photocopying', 'document printing', 'banners', 'large format'],
    parentId: 'other-services',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'other-custom',
    label: 'Bespoke Creation',
    productType: 'other',
    defaultUnit: 'pcs',
    aliases: ['custom gifts', 'engraved awards', 'plaques', 'custom orders'],
    parentId: 'other',
    variantAxes: [],
    attributes: [],
  },
  {
    id: 'other-custom-gifts',
    label: 'Engraved Wooden Awards, Custom Glass Plaques',
    productType: 'other',
    defaultUnit: 'pcs',
    aliases: ['custom gifts', 'wooden awards', 'glass plaques', 'engraved gifts'],
    parentId: 'other-custom',
    variantAxes: [],
    attributes: [],
  },
];

type RmfV3CategorySeed = [
  id: string,
  label: string,
  productType: string,
  defaultUnit: string,
  aliases: string[],
  parentId?: string | null
];

const rmfV3CategorySeeds: RmfV3CategorySeed[] = [
  ['grocery', 'Groceries & Fresh Produce', 'fresh_food', 'kg', ['grocery', 'groceries', 'fresh produce', 'vegetables', 'fruits', 'meat', 'dairy', 'pantry'], null],
  ['food', 'Food & Beverage', 'prepared_food', 'pcs', ['food', 'prepared food', 'restaurant', 'fast food', 'burgers', 'pizza', 'fried chicken', 'cafe'], null],
  ['bakery', 'Bakery & Patisserie', 'bakery_good', 'pcs', ['bakery', 'patisserie', 'bread', 'cake', 'pastry', 'desserts'], null],
  ['fashion', 'Fashion & Apparel', 'apparel', 'pcs', ['fashion', 'apparel', 'clothing', 'garments', 'textiles', 'accessories'], null],
  ['shoes', 'Shoes & Footwear', 'footwear', 'pair', ['shoes', 'footwear', 'sneakers', 'boots', 'sandals', 'heels'], null],
  ['sportswear', 'Sportswear, Fitness & Outdoor', 'sportswear', 'pcs', ['sportswear', 'fitness', 'outdoor', 'athletic apparel', 'sports equipment'], null],
  ['hardware', 'Hardware, Tools & Construction', 'hardware_tool', 'pcs', ['hardware', 'tools', 'construction', 'building materials', 'plumbing', 'electrical'], null],
  ['handicrafts', 'Handicrafts & Rwandan Artisanship', 'artisan_good', 'pcs', ['handicrafts', 'artisan', 'agaseke', 'imigongo', 'rwandan art'], null],
  ['home', 'Home, Furniture & Kitchen', 'home_good', 'pcs', ['home', 'furniture', 'kitchen', 'decor', 'household'], null],
  ['electronics', 'Electronics & Tech', 'electronics', 'pcs', ['electronics', 'tech', 'mobile', 'computers', 'solar', 'gaming'], null],
  ['cosmetics', 'Cosmetics, Beauty & Health', 'health_and_beauty', 'pcs', ['cosmetics', 'beauty', 'health', 'skincare', 'makeup', 'wellness'], null],
  ['automotive', 'Automotive, Moto & Transport', 'automotive', 'pcs', ['automotive', 'moto', 'transport', 'car parts', 'tyres'], null],
  ['education', 'Stationery, Books, Toys & Learning', 'education', 'pcs', ['stationery', 'books', 'toys', 'learning', 'education'], null],
  ['food-fastfood', 'Fast Food & Quick Service', 'prepared_food', 'pcs', ['fast food', 'quick service', 'burgers', 'pizza', 'fried chicken'], 'food'],
  ['food-fastfood-burgers', 'Burgers', 'prepared_food', 'pcs', ['beef burger', 'chicken burger', 'veggie burger', 'smash burger', 'cheese burger'], 'food-fastfood'],
  ['food-fastfood-pizza', 'Pizza', 'prepared_food', 'pcs', ['margherita', 'pepperoni', 'bbq chicken pizza', 'veggie pizza', 'thin crust'], 'food-fastfood'],
  ['food-fastfood-chicken', 'Fried Chicken', 'prepared_food', 'pcs', ['crispy chicken', 'spicy wings', 'chicken strips', 'grilled chicken'], 'food-fastfood'],
  ['food-fastfood-chips', 'Chips & Fries', 'prepared_food', 'pcs', ['fries', 'chips', 'wedges', 'loaded fries', 'sweet potato fries'], 'food-fastfood'],
  ['food-fastfood-hotdogs', 'Hotdogs & Sausages', 'prepared_food', 'pcs', ['hotdog', 'chilli dog', 'cheese dog', 'bratwurst', 'corn dog'], 'food-fastfood'],
  ['food-fastfood-sandwiches', 'Sandwiches & Wraps', 'prepared_food', 'pcs', ['sandwich', 'wrap', 'shawarma', 'panini', 'toastie', 'sub'], 'food-fastfood'],
  ['food-fastfood-tacos', 'Tacos & Mexican', 'prepared_food', 'pcs', ['tacos', 'burritos', 'quesadillas', 'nachos', 'churros'], 'food-fastfood'],
  ['food-local', 'Rwandan & East African Cuisine', 'prepared_food', 'pcs', ['rwandan food', 'east african food', 'isombe', 'matoke', 'brochettes'], 'food'],
  ['food-local-staples', 'Rwandan Staples', 'prepared_food', 'pcs', ['isombe', 'matoke', 'ugali', 'ibiharage', 'agatogo', 'ubugari'], 'food-local'],
  ['food-local-grills', 'Grilled Meats', 'prepared_food', 'pcs', ['brochettes', 'nyama choma', 'bbq ribs', 'mishkaki'], 'food-local'],
  ['food-local-soups', 'Soups & Stews', 'prepared_food', 'pot', ['goat stew', 'bean soup', 'fish soup', 'peanut soup'], 'food-local'],
  ['food-local-streetfood', 'Street Food', 'prepared_food', 'pcs', ['rolex', 'chapati', 'samosa', 'mandazi', 'roasted maize'], 'food-local'],
  ['food-local-breakfast', 'Local Breakfast', 'prepared_food', 'pcs', ['uji', 'chapati and tea', 'boiled eggs', 'matoke and eggs'], 'food-local'],
  ['food-continental', 'Continental & International Cuisine', 'prepared_food', 'pcs', ['continental food', 'international food', 'asian', 'western', 'vegan'], 'food'],
  ['food-continental-western', 'Western Cuisine', 'prepared_food', 'pcs', ['pasta', 'steak meal', 'fish and chips', 'quiche'], 'food-continental'],
  ['food-continental-asian', 'Asian Cuisine', 'prepared_food', 'pcs', ['fried rice', 'stir fry', 'dumplings', 'biryani', 'sushi', 'ramen'], 'food-continental'],
  ['food-continental-middleeast', 'Middle Eastern Cuisine', 'prepared_food', 'pcs', ['shawarma', 'falafel', 'hummus', 'kebabs', 'tabbouleh'], 'food-continental'],
  ['food-continental-vegan', 'Vegan & Vegetarian', 'prepared_food', 'pcs', ['vegan bowl', 'tofu', 'jackfruit', 'lentil curry', 'plant based'], 'food-continental'],
  ['food-cafe', 'Cafe, Juice Bar & Desserts', 'prepared_food', 'pcs', ['cafe', 'juice bar', 'desserts', 'coffee', 'smoothies'], 'food'],
  ['food-cafe-drinks', 'Cafe Drinks', 'prepared_food', 'cup', ['espresso', 'cappuccino', 'latte', 'cold brew', 'smoothie', 'juice'], 'food-cafe'],
  ['food-cafe-lightbites', 'Light Bites', 'prepared_food', 'pcs', ['salad', 'wrap', 'parfait', 'acai bowl', 'overnight oats'], 'food-cafe'],
  ['food-cafe-desserts', 'Desserts', 'prepared_food', 'pcs', ['waffles', 'pancakes', 'crepes', 'ice cream', 'brownies'], 'food-cafe'],
  ['food-catering', 'Catering & Bulk Orders', 'prepared_food', 'tray', ['catering', 'bulk food', 'event buffet', 'office lunch'], 'food'],
  ['food-catering-events', 'Event Catering', 'prepared_food', 'tray', ['wedding catering', 'conference catering', 'school meals'], 'food-catering'],
  ['food-catering-snackplatter', 'Snack Platters', 'prepared_food', 'tray', ['samosa platter', 'kebab tray', 'finger foods', 'canapes'], 'food-catering'],
  ['food-catering-breakfast', 'Breakfast Packages', 'prepared_food', 'tray', ['continental breakfast', 'fruit platter', 'pastry basket'], 'food-catering'],
  ['food-catering-bbq', 'BBQ & Grill Packages', 'prepared_food', 'tray', ['bbq package', 'whole roast chicken', 'goat roast'], 'food-catering'],
  ['food-health', 'Health-Conscious & Diet Food', 'prepared_food', 'pcs', ['healthy food', 'diet food', 'keto', 'high protein', 'detox'], 'food'],
  ['food-health-keto', 'Keto & Low-Carb', 'prepared_food', 'pcs', ['keto meal', 'low carb', 'cauliflower rice', 'zoodles'], 'food-health'],
  ['food-health-protein', 'High-Protein Meals', 'prepared_food', 'pcs', ['protein meal', 'grilled chicken bowl', 'tuna salad'], 'food-health'],
  ['food-health-detox', 'Detox & Cleanse', 'prepared_food', 'pcs', ['green smoothie', 'detox juice', 'chia pudding', 'superfood bowl'], 'food-health'],

  ['agriculture', 'Agriculture & Farming', 'agriculture', 'kg', ['agriculture', 'farming', 'farm gate', 'livestock', 'seedlings'], null],
  ['agriculture-crops', 'Raw Farm Produce', 'agriculture', 'kg', ['farm produce', 'farm gate', 'cereals', 'legumes'], 'agriculture'],
  ['agriculture-crops-cereals', 'Cereals', 'agriculture', 'kg', ['maize cobs', 'sorghum', 'wheat', 'barley', 'millet', 'teff'], 'agriculture-crops'],
  ['agriculture-crops-legumes', 'Legumes', 'agriculture', 'kg', ['fresh beans', 'soybeans', 'groundnuts', 'peas', 'cowpeas'], 'agriculture-crops'],
  ['agriculture-crops-horticulture', 'Horticulture', 'agriculture', 'kg', ['tomatoes', 'capsicum', 'cabbage', 'broccoli', 'chillies'], 'agriculture-crops'],
  ['agriculture-crops-roots', 'Root Crops', 'agriculture', 'kg', ['cassava', 'sweet potatoes', 'yams', 'taro', 'arrow roots'], 'agriculture-crops'],
  ['agriculture-crops-export', 'Export Crops', 'agriculture', 'kg', ['coffee cherries', 'tea leaf', 'pyrethrum', 'macadamia', 'vanilla'], 'agriculture-crops'],
  ['agriculture-crops-fruits', 'Farm Fruits', 'agriculture', 'kg', ['avocados', 'bananas', 'mangoes', 'passion fruit', 'pineapples'], 'agriculture-crops'],
  ['agriculture-livestock', 'Livestock & Animal Products', 'agriculture', 'pcs', ['livestock', 'animal products', 'cattle', 'poultry', 'fish'], 'agriculture'],
  ['agriculture-livestock-cattle', 'Cattle & Ruminants', 'agriculture', 'pcs', ['dairy cows', 'beef cattle', 'calves', 'goats', 'sheep', 'pigs'], 'agriculture-livestock'],
  ['agriculture-livestock-poultry', 'Poultry', 'agriculture', 'pcs', ['live chickens', 'day-old chicks', 'ducks', 'turkeys', 'quail'], 'agriculture-livestock'],
  ['agriculture-livestock-products', 'Animal Products', 'agriculture', 'litre', ['raw milk', 'ghee', 'farm honey', 'beeswax', 'manure', 'wool'], 'agriculture-livestock'],
  ['agriculture-livestock-fish', 'Aquaculture', 'agriculture', 'pcs', ['live tilapia', 'catfish fingerlings', 'fish pond inputs'], 'agriculture-livestock'],
  ['agriculture-inputs', 'Agri-Inputs & Chemicals', 'agriculture', 'pcs', ['fertilizer', 'pesticide', 'seeds', 'chemicals'], 'agriculture'],
  ['agriculture-inputs-fertilizer', 'Fertilizers', 'agriculture', 'kg', ['dap', 'urea', 'npk', 'compost', 'lime'], 'agriculture-inputs'],
  ['agriculture-inputs-pesticides', 'Crop Protection', 'agriculture', 'litre', ['pesticides', 'herbicides', 'fungicides', 'biopesticides'], 'agriculture-inputs'],
  ['agriculture-inputs-seeds', 'Seeds', 'agriculture', 'pack', ['certified seeds', 'hybrid seeds', 'vegetable seeds', 'cover crop seeds'], 'agriculture-inputs'],
  ['agriculture-seedlings', 'Seedlings & Planting Material', 'agriculture', 'pcs', ['seedlings', 'planting material', 'fruit seedlings'], 'agriculture'],
  ['agriculture-seedlings-fruit', 'Fruit Seedlings', 'agriculture', 'pcs', ['avocado seedling', 'mango seedling', 'passion fruit', 'banana suckers'], 'agriculture-seedlings'],
  ['agriculture-seedlings-vegetable', 'Vegetable Seedlings', 'agriculture', 'pcs', ['tomato seedling', 'cabbage seedling', 'pepper seedling'], 'agriculture-seedlings'],
  ['agriculture-seedlings-tree', 'Trees', 'agriculture', 'pcs', ['timber trees', 'shade trees', 'ornamental trees', 'medicinal plants'], 'agriculture-seedlings'],
  ['agriculture-beekeeping', 'Beekeeping & Apiculture', 'agriculture', 'pcs', ['beekeeping', 'apiculture', 'hives', 'honey'], 'agriculture'],
  ['agriculture-beekeeping-equipment', 'Beekeeping Equipment', 'agriculture', 'pcs', ['langstroth hive', 'top bar hive', 'smoker', 'bee suit'], 'agriculture-beekeeping'],
  ['agriculture-beekeeping-products', 'Bee Products', 'agriculture', 'kg', ['raw honey', 'beeswax', 'propolis', 'royal jelly'], 'agriculture-beekeeping'],
  ['agriculture-irrigation', 'Irrigation & Water Management', 'agriculture', 'pcs', ['irrigation', 'water pumps', 'drip kits'], 'agriculture'],
  ['agriculture-irrigation-drip', 'Drip Irrigation', 'agriculture', 'pcs', ['drip kit', 'drip tape', 'emitters', 'filters'], 'agriculture-irrigation'],
  ['agriculture-irrigation-sprinkler', 'Sprinkler Irrigation', 'agriculture', 'pcs', ['sprinkler head', 'impact sprinkler', 'hose pipe'], 'agriculture-irrigation'],
  ['agriculture-irrigation-pumps', 'Water Pumps', 'agriculture', 'pcs', ['water pump', 'solar pump', 'submersible pump', 'petrol pump'], 'agriculture-irrigation'],

  ['services', 'Services & Professional Tasks', 'service', 'job', ['services', 'professional tasks', 'repair', 'creative services', 'tutoring'], null],
  ['services-creative', 'Creative & Design Services', 'service', 'job', ['tailoring', 'printing', 'photography', 'graphic design', 'digital services'], 'services'],
  ['services-creative-tailoring', 'Tailoring', 'service', 'job', ['garment alteration', 'custom tailoring', 'uniform making', 'embroidery'], 'services-creative'],
  ['services-creative-printing', 'Print Services', 'service', 'page', ['printing', 'photocopying', 'banners', 'business cards', 'signage'], 'services-creative'],
  ['services-creative-photography', 'Photography & Video', 'service', 'job', ['event photography', 'portrait session', 'video production'], 'services-creative'],
  ['services-creative-graphic', 'Graphic Design', 'service', 'job', ['logo design', 'flyer design', 'brand identity', 'packaging'], 'services-creative'],
  ['services-creative-digital', 'Digital Services', 'service', 'job', ['website development', 'app development', 'seo', 'social media management'], 'services-creative'],
  ['services-repair', 'Repair & Maintenance', 'service', 'job', ['repair', 'maintenance', 'electronics repair', 'home repairs'], 'services'],
  ['services-repair-electronics', 'Electronics Repair', 'service', 'job', ['phone screen repair', 'laptop repair', 'tv repair', 'console repair'], 'services-repair'],
  ['services-repair-domestic', 'Home Repairs', 'service', 'job', ['plumbing', 'electrical', 'tiling', 'painting', 'door fixing'], 'services-repair'],
  ['services-repair-appliances', 'Appliance Servicing', 'service', 'job', ['fridge repair', 'washing machine repair', 'generator repair', 'microwave repair'], 'services-repair'],
  ['services-repair-auto', 'Auto Repairs', 'service', 'job', ['mechanical repairs', 'tyre change', 'car wash', 'oil change', 'diagnostics'], 'services-repair'],
  ['services-repair-furniture', 'Furniture Restoration', 'service', 'job', ['reupholstering', 'wood polishing', 'chair repair', 'mattress replacement'], 'services-repair'],
  ['services-logistics', 'Delivery & Logistics', 'service', 'trip', ['delivery', 'logistics', 'moto courier', 'freight', 'cold chain'], 'services'],
  ['services-logistics-moto', 'Moto Courier', 'service', 'trip', ['express delivery', 'same-day parcels', 'last-mile delivery'], 'services-logistics'],
  ['services-logistics-freight', 'Heavy Freight', 'service', 'trip', ['furniture moving', 'cross-border cargo', 'haulage'], 'services-logistics'],
  ['services-logistics-cold', 'Cold Chain', 'service', 'trip', ['refrigerated transport', 'grocery delivery', 'pharmaceutical delivery'], 'services-logistics'],
  ['services-logistics-international', 'International Logistics', 'service', 'job', ['air freight', 'sea freight', 'customs clearance', 'import export'], 'services-logistics'],
  ['services-beauty', 'Beauty & Wellness Services', 'service', 'job', ['hair services', 'nails', 'spa', 'barber'], 'services'],
  ['services-education', 'Tutoring & Training', 'service', 'session', ['tutoring', 'training', 'lessons', 'exam prep'], 'services'],
  ['services-construction', 'Construction & Trade Services', 'service', 'job', ['construction', 'renovation', 'finishing', 'installation'], 'services'],
  ['services-cleaning', 'Cleaning & Hygiene Services', 'service', 'job', ['home cleaning', 'commercial cleaning', 'laundry', 'pest control'], 'services'],
  ['services-health', 'Health & Medical Services', 'service', 'session', ['consultation', 'nursing', 'dental', 'therapy', 'optician'], 'services'],
  ['services-financial', 'Financial Services', 'service', 'job', ['accounting', 'legal services', 'insurance services'], 'services'],

  ['events', 'Events, Rentals & Entertainment', 'event', 'pcs', ['events', 'rentals', 'entertainment', 'party supplies', 'event decor'], null],
  ['events-decor', 'Event Decor & Setup', 'event', 'pcs', ['event decor', 'flowers', 'balloons', 'backdrops', 'lighting'], 'events'],
  ['events-decor-flowers', 'Florals', 'event', 'pcs', ['fresh arrangements', 'bouquets', 'wreaths', 'centrepieces', 'arches'], 'events-decor'],
  ['events-decor-furniture', 'Event Furniture', 'event', 'pcs', ['chairs', 'round tables', 'tents', 'podiums', 'cocktail tables'], 'events-decor'],
  ['events-decor-balloons', 'Balloons', 'event', 'pcs', ['balloon arrangements', 'foil balloons', 'balloon arches'], 'events-decor'],
  ['events-decor-lighting', 'Event Lighting', 'event', 'pcs', ['fairy lights', 'neon signs', 'led uplighting', 'gobo projectors'], 'events-decor'],
  ['events-decor-backdrops', 'Backdrops', 'event', 'pcs', ['photo backdrop', 'floral wall', 'sequin panels', 'step and repeat'], 'events-decor'],
  ['events-entertainment', 'Entertainment & Performance', 'event', 'job', ['dj', 'live band', 'mc', 'videography', 'performers'], 'events'],
  ['events-party', 'Party & Celebration Supplies', 'event', 'pcs', ['party supplies', 'disposables', 'decor supplies', 'candles', 'gift bags'], 'events'],
  ['events-rentals', 'Equipment Rentals', 'event', 'day', ['equipment rental', 'av rental', 'catering equipment', 'furniture hire'], 'events'],

  ['property', 'Real Estate & Property', 'property', 'pcs', ['property', 'real estate', 'houses', 'apartments', 'land'], null],
  ['property-residential', 'Residential Property', 'property', 'pcs', ['residential property', 'houses', 'apartments', 'short stays'], 'property'],
  ['property-residential-sale', 'Residential For Sale', 'property', 'pcs', ['house for sale', 'apartment for sale', 'villa', 'duplex'], 'property-residential'],
  ['property-residential-rent', 'Residential To Rent', 'property', 'pcs', ['house to rent', 'apartment rent', 'studio apartment', 'room rental'], 'property-residential'],
  ['property-residential-shortlet', 'Short-Stay Property', 'property', 'pcs', ['short let', 'guesthouse', 'holiday home', 'serviced apartment'], 'property-residential'],
  ['property-commercial', 'Commercial Property', 'property', 'pcs', ['office space', 'retail shop', 'warehouse', 'commercial property'], 'property'],
  ['property-commercial-office', 'Office Spaces', 'property', 'pcs', ['office space', 'co-working', 'business centre', 'executive suite'], 'property-commercial'],
  ['property-commercial-retail', 'Retail Spaces', 'property', 'pcs', ['shop', 'market stall', 'kiosk', 'showroom', 'restaurant space'], 'property-commercial'],
  ['property-commercial-warehouse', 'Industrial & Warehouses', 'property', 'pcs', ['warehouse', 'cold storage', 'industrial shed', 'storage unit'], 'property-commercial'],
  ['property-land', 'Land & Plots', 'property', 'pcs', ['land', 'plots', 'serviced land', 'commercial land'], 'property'],
  ['property-services', 'Property Services', 'property', 'job', ['real estate agency', 'property valuation', 'title deed', 'surveying'], 'property'],

  ['pets', 'Pets & Animal Care', 'pet', 'pcs', ['pets', 'animal care', 'dogs', 'cats', 'pet food'], null],
  ['pets-animals', 'Live Animals', 'pet', 'pcs', ['live animals', 'dogs', 'cats', 'birds', 'fish'], 'pets'],
  ['pets-animals-dogs', 'Dogs', 'pet', 'pcs', ['puppies', 'adult dogs', 'rottweiler', 'german shepherd', 'labs'], 'pets-animals'],
  ['pets-animals-cats', 'Cats', 'pet', 'pcs', ['kittens', 'adult cats', 'persian', 'siamese'], 'pets-animals'],
  ['pets-animals-birds', 'Birds', 'pet', 'pcs', ['parrots', 'canaries', 'love birds', 'budgerigars'], 'pets-animals'],
  ['pets-animals-small', 'Small Pets', 'pet', 'pcs', ['rabbits', 'guinea pigs', 'hamsters', 'turtles'], 'pets-animals'],
  ['pets-animals-aquatic', 'Aquatic Pets', 'pet', 'pcs', ['ornamental fish', 'goldfish', 'aquarium plants', 'snails'], 'pets-animals'],
  ['pets-food', 'Pet Food & Nutrition', 'pet', 'pcs', ['pet food', 'dog food', 'cat food', 'bird seed'], 'pets'],
  ['pets-food-dog', 'Dog Food', 'pet', 'kg', ['dry kibble', 'wet dog food', 'dog treats', 'puppy milk'], 'pets-food'],
  ['pets-food-cat', 'Cat Food', 'pet', 'kg', ['cat kibble', 'wet cat food', 'cat treats', 'kitten formula'], 'pets-food'],
  ['pets-food-other', 'Other Pet Food', 'pet', 'pcs', ['bird seed', 'fish food', 'rabbit pellets', 'reptile food'], 'pets-food'],
  ['pets-accessories', 'Pet Accessories & Care', 'pet', 'pcs', ['pet accessories', 'grooming', 'collars', 'beds', 'aquariums'], 'pets'],
  ['pets-accessories-grooming', 'Pet Grooming', 'pet', 'pcs', ['dog shampoo', 'cat shampoo', 'flea treatment', 'nail clippers'], 'pets-accessories'],
  ['pets-accessories-gear', 'Pet Gear & Housing', 'pet', 'pcs', ['collars', 'leads', 'harnesses', 'pet carriers', 'beds', 'kennels'], 'pets-accessories'],
  ['pets-accessories-toys', 'Pet Toys & Enrichment', 'pet', 'pcs', ['chew toys', 'catnip', 'laser pointers', 'puzzle feeders'], 'pets-accessories'],
  ['pets-accessories-health', 'Vet & Health', 'pet', 'pcs', ['dewormers', 'pet vitamins', 'tick treatment', 'pet first aid'], 'pets-accessories'],
  ['pets-accessories-aquarium', 'Aquariums', 'pet', 'pcs', ['fish tanks', 'filters', 'heaters', 'aquarium gravel'], 'pets-accessories'],

  ['solar-energy', 'Solar, Renewable Energy & Clean Water', 'solar_energy', 'pcs', ['solar', 'renewable energy', 'clean water', 'water filters'], null],
  ['solar-energy-solar', 'Solar Power Systems', 'solar_energy', 'pcs', ['solar panels', 'solar batteries', 'inverters', 'solar kits'], 'solar-energy'],
  ['solar-energy-solar-panels', 'Solar Panels', 'solar_energy', 'pcs', ['monocrystalline', 'polycrystalline', 'flexible panel', 'portable solar kit'], 'solar-energy-solar'],
  ['solar-energy-solar-batteries', 'Solar Batteries', 'solar_energy', 'pcs', ['lithium battery', 'lifepo4', 'lead acid', 'gel battery'], 'solar-energy-solar'],
  ['solar-energy-solar-inverters', 'Solar Inverters', 'solar_energy', 'pcs', ['hybrid inverter', 'off grid inverter', 'grid tied inverter', 'charge controller'], 'solar-energy-solar'],
  ['solar-energy-solar-accessories', 'Solar Accessories', 'solar_energy', 'pcs', ['mounting brackets', 'mc4 connectors', 'combiner boxes', 'dc isolators'], 'solar-energy-solar'],
  ['solar-energy-water', 'Clean Water & Sanitation', 'solar_energy', 'pcs', ['water pumps', 'water filters', 'water tanks', 'rain harvesting'], 'solar-energy'],
  ['solar-energy-water-pumps', 'Water Pumps', 'solar_energy', 'pcs', ['solar water pump', 'submersible pump', 'hand pump', 'borehole pump'], 'solar-energy-water'],
  ['solar-energy-water-treatment', 'Water Treatment', 'solar_energy', 'pcs', ['water filter', 'uv sterilizer', 'ro system', 'chlorine dispenser'], 'solar-energy-water'],
  ['solar-energy-water-tanks', 'Water Tanks', 'solar_energy', 'pcs', ['plastic tank', 'underground cistern', 'bladder tank', 'water bowser'], 'solar-energy-water'],
  ['solar-energy-cooking', 'Clean Cooking', 'solar_energy', 'pcs', ['clean stove', 'biogas', 'improved cookstove'], 'solar-energy'],
  ['solar-energy-cooking-stoves', 'Clean Stoves', 'solar_energy', 'pcs', ['improved cookstove', 'ethanol stove', 'pellet stove', 'rocket stove'], 'solar-energy-cooking'],
  ['solar-energy-cooking-biogas', 'Biogas Systems', 'solar_energy', 'pcs', ['biogas digester', 'biogas pipes', 'gas burners', 'bio slurry'], 'solar-energy-cooking'],

  ['office-business', 'Office & Business Supplies', 'office_business', 'pcs', ['office', 'business supplies', 'office furniture', 'pos', 'signage'], null],
  ['office-business-furniture', 'Office Furniture', 'office_business', 'pcs', ['office desks', 'ergonomic chairs', 'filing cabinets'], 'office-business'],
  ['office-business-furniture-desks', 'Office Desks', 'office_business', 'pcs', ['executive desk', 'l-shape desk', 'standing desk', 'workstation'], 'office-business-furniture'],
  ['office-business-furniture-seating', 'Office Seating', 'office_business', 'pcs', ['ergonomic chair', 'visitor chair', 'conference chair', 'executive chair'], 'office-business-furniture'],
  ['office-business-furniture-storage', 'Office Storage', 'office_business', 'pcs', ['filing cabinet', 'pedestal', 'locker', 'shelving'], 'office-business-furniture'],
  ['office-business-supplies', 'Office Consumables & Supplies', 'office_business', 'pcs', ['paper', 'stationery', 'ink', 'toner', 'diaries'], 'office-business'],
  ['office-business-supplies-paper', 'Paper & Stationery', 'office_business', 'ream', ['a4 reams', 'letterheads', 'envelopes', 'labels', 'ncr forms'], 'office-business-supplies'],
  ['office-business-supplies-ink', 'Ink & Toner', 'office_business', 'pcs', ['printer cartridges', 'toner', 'drum units', 'ribbons'], 'office-business-supplies'],
  ['office-business-supplies-daily', 'Daily Office Supplies', 'office_business', 'pcs', ['diaries', 'planners', 'calendars', 'folders', 'id holders'], 'office-business-supplies'],
  ['office-business-machines', 'Office Machines', 'office_business', 'pcs', ['printers', 'shredders', 'laminators', 'office phones'], 'office-business'],
  ['office-business-signage', 'Signage & Branding', 'office_business', 'pcs', ['billboards', 'roll-up banners', 'acrylic letters', 'branded merch'], 'office-business'],
  ['office-business-fintech', 'Payment & Fintech Equipment', 'office_business', 'pcs', ['pos terminal', 'mpo card reader', 'cash counter', 'qr code stickers'], 'office-business'],

  ['finance', 'Financial Products & Insurance', 'finance', 'pcs', ['finance', 'insurance', 'savings', 'investment'], null],
  ['finance-insurance', 'Insurance Products', 'finance', 'pcs', ['health insurance', 'motor insurance', 'property insurance', 'life insurance'], 'finance'],
  ['finance-insurance-health', 'Health Insurance', 'finance', 'pcs', ['mutuelle de sante', 'private health plan', 'hospital cash'], 'finance-insurance'],
  ['finance-insurance-general', 'General Insurance', 'finance', 'pcs', ['motor insurance', 'property insurance', 'crop insurance', 'life insurance'], 'finance-insurance'],
  ['finance-savings', 'Savings & Investment Products', 'finance', 'pcs', ['sacco', 'cooperative', 'digital savings', 'investment'], 'finance'],
  ['finance-savings-sacco', 'SACCO & Cooperative', 'finance', 'pcs', ['sacco shares', 'cooperative deposits', 'village savings group'], 'finance-savings'],
  ['finance-savings-digital', 'Digital Savings', 'finance', 'pcs', ['mobile savings', 'digital investment', 'unit trust'], 'finance-savings'],

  ['other-recycling', 'Recycling & Waste', 'other', 'kg', ['recycling', 'waste', 'scrap', 'plastic bottles', 'metals'], 'other'],
  ['other-recycling-plastics', 'Plastic Recyclables', 'other', 'kg', ['plastic bottles', 'plastic bags', 'hdpe', 'pet recyclables'], 'other-recycling'],
  ['other-recycling-metals', 'Metal Recyclables', 'other', 'kg', ['scrap iron', 'aluminium cans', 'copper wire', 'steel scrap'], 'other-recycling'],
  ['other-recycling-paper', 'Paper Recyclables', 'other', 'kg', ['cardboard', 'newspapers', 'office waste paper'], 'other-recycling'],
  ['other-custom-awards', 'Awards & Recognition', 'other', 'pcs', ['engraved trophies', 'crystal plaques', 'wooden awards', 'medal sets'], 'other-custom'],
  ['other-custom-branded', 'Branded Items', 'other', 'pcs', ['promotional items', 'custom packaging', 'bespoke labels', 'branded gifts'], 'other-custom'],
  ['other-custom-events', 'Event Custom Items', 'other', 'pcs', ['event decor', 'bespoke floral', 'custom venue setups', 'themed props'], 'other-custom'],
  ['other-miscellaneous', 'Miscellaneous', 'other', 'pcs', ['miscellaneous', 'unlisted items', 'manual categorisation'], 'other'],
  ['other-misc-uncategorized', 'Unlisted Items', 'other', 'pcs', ['uncategorized', 'unlisted', 'manual category', 'submit with details'], 'other-miscellaneous'],
];

const mergeRmfV3Catalog = (existing: CatalogCategory[]): CatalogCategory[] => {
  const byId = new Map(existing.map(category => [category.id, category]));
  rmfV3CategorySeeds.forEach(([id, label, productType, defaultUnit, aliases, parentId]) => {
    const current = byId.get(id);
    const mergedAliases = Array.from(new Set([...(current?.aliases || []), ...aliases]));
    byId.set(id, {
      ...(current || { variantAxes: [], attributes: [] }),
      id,
      label,
      productType,
      defaultUnit,
      aliases: mergedAliases,
      synonyms: Array.from(new Set([...(current?.synonyms || []), ...mergedAliases])),
      searchBoost: parentId ? 1 : 1.15,
      isActive: true,
      version: 3,
      parentId: parentId ?? null,
    });
  });
  return Array.from(byId.values());
};

export const catalogCategories: CatalogCategory[] = mergeRmfV3Catalog(rmfCoreCatalogCategories);

const aliasMap = new Map<string, CatalogCategory>();
const categoryById = new Map(catalogCategories.map(category => [category.id, category]));
const categoryDepth = (category: CatalogCategory): number => {
  let depth = 0;
  let parentId = category.parentId || null;
  while (parentId) {
    const parent = categoryById.get(parentId);
    if (!parent) break;
    depth++;
    parentId = parent.parentId || null;
  }
  return depth;
};

const addAlias = (key: string, category: CatalogCategory) => {
  const normalized = key.toLowerCase();
  const existing = aliasMap.get(normalized);
  if (!existing || categoryDepth(category) > categoryDepth(existing)) {
    aliasMap.set(normalized, category);
  }
};

for (const category of catalogCategories) {
  addAlias(category.id, category);
  addAlias(category.label, category);
  category.aliases.forEach(alias => addAlias(alias, category));
}

const singularize = (value: string) => value.endsWith('s') && value.length > 3 ? value.slice(0, -1) : value;

const withInheritedCatalogFields = (category: CatalogCategory): CatalogCategory => {
  let inheritedAxes = [...category.variantAxes];
  let inheritedAttributes = [...category.attributes];
  let parentId = category.parentId || null;

  while ((inheritedAxes.length === 0 || inheritedAttributes.length === 0) && parentId) {
    const parent = categoryById.get(parentId);
    if (!parent) break;
    if (inheritedAxes.length === 0 && parent.variantAxes.length > 0) {
      inheritedAxes = parent.variantAxes;
    }
    if (inheritedAttributes.length === 0 && parent.attributes.length > 0) {
      inheritedAttributes = parent.attributes;
    }
    parentId = parent.parentId || null;
  }

  return {
    ...category,
    variantAxes: inheritedAxes,
    attributes: inheritedAttributes,
  };
};

export const resolveCatalogCategory = (value: unknown): CatalogCategory => {
  const normalized = String(value || '').trim().toLowerCase();
  const normalizedTokens = normalized.split(/[^a-z0-9]+/).filter(Boolean).map(singularize);
  const resolved = aliasMap.get(normalized)
    || catalogCategories
      .slice()
      .sort((left, right) => categoryDepth(right) - categoryDepth(left))
      .find(category => {
        const candidates = [category.id, category.label, ...category.aliases, ...(category.synonyms || [])]
          .map(candidate => candidate.toLowerCase());
        return candidates.some(candidate => {
          const singularCandidate = singularize(candidate);
          return normalized.includes(candidate)
            || normalized.includes(singularCandidate)
            || normalizedTokens.includes(singularCandidate);
        });
      })
    || catalogCategories[catalogCategories.length - 1];
  return withInheritedCatalogFields(resolved);
};
