'use client';
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'kin';

const translations = {
  en: {
    // General
    cancel: 'Cancel',
    loading: 'Loading...',
    save: 'Save',
    success: 'Success!',
    error: 'An error occurred',
    items: 'items',
    product: 'Product',
    // Nav
    nav_login: 'Log In',
    nav_markets: 'Markets',
    nav_cart: 'Cart',
    nav_wishlist: 'Wishlist',
    nav_my_orders: 'My Orders',
    site_name: 'Rwandan Market Facilitator',
    nav_terms: 'Terms',
    nav_privacy: 'Privacy',
    nav_hub: 'Marketplace',
    nav_artifacts: 'Products',
    nav_mandates: 'Orders',
    nav_sign_in: 'Sign In',
    nav_join: 'Join RMF',
    // General
    official_facilitator: 'Official Marketplace',
    official_infrastructure: 'Verified Platform',
    regional_hubs: 'Local Markets',
    heritage_artifacts: 'Products',
    heritage_discovery: 'Shop',
    trending_region: 'Trending Now',
    new_standards: 'Premium Quality',
    verified_facility: 'Verified',
    active_facilitators: 'Active Sellers',
    creative_partners: 'Local Artisans',
    secure_transit: 'Secure Delivery',
    citizen_approval: 'Customer Rating',
    commercial_fulfillment: 'Order Fulfilled',
    mandate_id: 'Order ID',
    lifecycle_stage: 'Order Status',
    review_mandate: 'Manage Order',
    refine_discovery: 'Filter Products',
    find_hub_placeholder: 'Search markets...',
    no_hubs_deployed: 'No markets yet',
    secure_hubs_title: 'Verified Rwandan Markets',
    secure_hubs_desc: '"Every market on RMF is verified. Sellers are checked for business registration and quality standards."',
    verified_partner: 'Verified Seller',
    network_reach: 'Delivery Range',
    acquisitions: 'Orders',
    facilitator_support: 'Customer Support',
    // Detail Pages
    accessing_market_hub: 'Loading market...',
    unveiling_heritage_artifact: 'Loading product...',
    verified_facilitation_hub: 'Verified Market',
    live_fleet_deployment: 'Live Rider Tracking',
    facilitators_active_near: 'Riders near',
    expand_logistics_view: 'View Map',
    close_tactical_view: 'Close Map',
    search_collection: 'Search products...',
    all_artifacts: 'All Products',
    the_collection: 'Products',
    quality_assurance: 'Quality Assured',
    customer_experience: 'Customer Reviews',
    master_artisan: 'Local Artisan',
    crafted_on_commission: 'Made to Order',
    in_facility_storage: 'In Stock',
    facilitation_brief: 'Product Description',
    save_to_heritage_list: 'Save to Wishlist',
    global_rating: 'Rating',
    items_found: 'Items Found',
    // Home
    home_hero_title: 'Rwanda\'s Best\nLocal Markets',
    home_hero_desc: 'Shop authentic products from verified local sellers across Rwanda. Pay with MoMo, get fast delivery to your door.',
    home_hero_cta: 'Browse Markets',
    home_explore_heading: 'Local Markets',
    home_search_placeholder: 'Search markets, products...',
    home_trending_products: 'Popular Products',
    home_trending_subtitle: 'Best sellers right now',
    view_all_markets: 'View All Markets',
    how_it_works_title: 'How It Works',
    how_it_works_subtitle: 'Simple, fast, and reliable — from your local market to your door.',
    step_1_title: '1. Place Your Order',
    step_1_desc: 'Browse products, add to cart, and pay with MTN MoMo or Airtel Money.',
    step_2_title: '2. Seller Prepares',
    step_2_desc: 'Your verified seller gets the notification and prepares your order.',
    step_3_title: '3. Fast Delivery',
    step_3_desc: 'A local moto-rider picks up and delivers to your exact address.',
    trust_title: 'Shop with Confidence',
    trust_point_1_title: 'Buyer Protection',
    trust_point_1_desc: 'Every transaction is held in escrow until you confirm you received your order.',
    become_seller: 'Start Selling',
    active_sellers: 'Verified Sellers',
    shop_now: 'Shop Now',
    verified_sellers_title: 'Verified Sellers',
    verified_sellers_desc: 'Every seller is checked for business registration and quality before going live.',
    secure_payments_title: 'Secure Payments',
    secure_payments_desc: 'Pay safely with MoMo. Your money is held in escrow until delivery is confirmed.',
    trust_point_2_title: 'Verified Sellers',
    trust_point_2_desc: 'We only work with sellers who have valid business registration and meet our quality standards.',
    trust_point_3_title: 'Real-time Delivery Tracking',
    trust_point_3_desc: 'Track your rider live on the map from the market to your door.',
    facilitation_mission_title: 'Supporting Rwanda\'s',
    facilitation_mission_span: 'Local Economy.',
    artisan_testimonial: '"Since joining the platform, my sales have increased by 300%. Customers from across Kigali can now find my products."',
    master_weaver_label: 'Verified Seller, Kimironko Market',
    // Product
    product_add_to_cart: 'Add to Cart',
    product_buy_now: 'Buy Now',
    product_out_of_stock: 'Out of Stock',
    product_available: 'Available',
    product_price_on_quote: 'Price on Quote',
    product_messaging_quote: '📜 Messaging Quote',
    product_send_quote: '📩 Send Messaging Quote Request',
    product_by_command: 'By Command',
    product_made_in_rwanda: 'Made in Rwanda',
    product_off: 'OFF',
    verified_seller_label: 'Verified Artisan',
    // Cart
    cart_title: 'Your Cart',
    cart_empty: 'Your cart is empty',
    cart_empty_desc: 'Looks like you haven\'t added anything to your cart yet.',
    cart_checkout: 'Proceed to Checkout',
    cart_total: 'Total',
    cart_delivery: 'Delivery Fee',
    cart_subtotal: 'Subtotal',
    cart_estimated_total: 'Estimated Total',
    cart_proceed_checkout: 'Proceed to Checkout',
    cart_calculated_at_checkout: 'Calculated at checkout',
    start_shopping: 'Start Shopping',
    continue_shopping: 'Continue Shopping',
    items_added_to_cart: 'Items added to cart!',
    // Wishlist
    wishlist_subtitle: 'Keep track of your favorite local products.',
    wishlist_empty_title: 'Your wishlist is empty',
    wishlist_empty_desc: 'Discover amazing products from Rwanda\'s local markets.',
    // Orders
    orders_title: 'My Orders',
    orders_subtitle: 'View your order history and track active deliveries.',
    orders_empty: 'No orders yet',
    order_summary: 'Order Summary',
    total_paid: 'Total Paid',
    customer_reviews: 'Customer Reviews',
    track_order: 'Track Order',
    write_review: 'Write Review',
    submit_review: 'Submit Review',
    order: 'Order',
    products: 'product(s)',
    bespoke_item: 'Bespoke Item',
    no_orders_shopping: 'No orders found. Start shopping!',
    receipt: 'Receipt',
    review_title: 'Review Your Order',
    rate_seller: 'Rate Seller',
    rate_rider: 'Rate Rider',
    rate_market: 'Rate Marketplace Location',
    rate_item: 'Rate Item',
    seller_review_placeholder: 'How was the service and packaging?',
    rider_review_placeholder: 'Was the delivery fast and professional?',
    market_review_placeholder: 'How was the market cleanliness and safety?',
    product_review_placeholder: 'How was the quality of this item?',
    submit_all_reviews: 'Submit All Reviews',
    reviews_submitted: 'Reviews submitted successfully!',
    reviews_submit_failed: 'Failed to submit reviews. Please try again.',
    // Order Statuses
    status_pending: 'Pending Payment',
    status_paid: 'Paid',
    status_PAID: 'Paid',
    status_confirmed: 'Confirmed',
    status_processing: 'Processing',
    status_packing: 'Packing',
    status_ready_for_pickup: 'Ready for Pickup',
    status_rider_assigned: 'Rider Assigned',
    status_rider_at_store: 'Rider at Store',
    status_picked_up: 'Picked Up',
    status_en_route: 'En Route',
    status_in_transit: 'In Transit',
    status_arrived: 'Arrived',
    status_delivered: 'Delivered',
    status_cancelled: 'Cancelled',
    status_disputed: 'Disputed',
    // Dashboard
    dashboard_welcome: 'Welcome back',
    dashboard_manage: 'Manage your orders and account settings.',
    dashboard_view_all: 'View All Orders',
    dashboard_activity: 'Activity Overview',
    dashboard_orders_placed: 'Orders Placed',
    dashboard_wishlist_items: 'Items in Wishlist',
    dashboard_platform_activity: 'Platform Activity',
    dashboard_total_orders: 'Total Orders',
    dashboard_in_progress: 'In Progress',
    dashboard_delivered: 'Delivered',
    dashboard_ref_earnings: 'Ref. Earnings',
    dashboard_live_tracking: 'Live Delivery Tracking',
    dashboard_recent_history: 'Recent Purchase History',
    dashboard_view_complete: 'View Complete History',
    dashboard_no_deliveries: 'No active deliveries right now.',
    dashboard_no_deliveries_desc: 'Your orders will appear here once they are processed.',
    dashboard_no_history: 'No purchase history found.',
    dashboard_receipt: 'Receipt',
    dashboard_repeat: 'Repeat',
    dashboard_rate: 'Rate',
    dashboard_rate_purchase: 'Rate your purchase',
    dashboard_rate_experience: 'How was your experience with {seller}?',
    dashboard_leave_comment: 'Leave a comment (optional)',
    dashboard_wallet_balance: 'My Wallet Balance',
    dashboard_top_up: 'Top Up Wallet',
    dashboard_refer_earn: 'Refer & Earn',
    dashboard_refer_desc: 'Invite friends to Rwanda Marketplace and get RWF 1,000 when they make their first purchase!',
    dashboard_copy_link: 'Copy Invitation Link',
    dashboard_recurring: 'Recurring Deliveries',
    dashboard_no_subscriptions: 'No active subscriptions.',
    dashboard_next_delivery: 'Next Delivery',
    dashboard_track_map: 'Track on Live Map',
    transit_terminal: 'My Dashboard',
    reliability_rate: 'Completion Rate',
    service_rating: 'Customer Rating',
    verified_facilitator: 'Verified Rider',
    total_deliveries: 'Total Deliveries',
    lifetime_fulfillment: 'Lifetime total',
    active_mandate: 'Active Delivery',
    shopper: 'Shopper',
    seller: 'seller',
    buyer: 'buyer',
    link_copied: 'Referral link copied!',
    review_submitted_thanks: 'Thank you for your feedback!',
    review_submit_failed: 'Failed to submit review',
    pause: 'Pause',
    // Markets
    markets_title: "Explore Rwanda's Markets",
    markets_subtitle: 'Browse through vibrant public markets and verified independent shops. Direct from source to your door.',
    markets_search_placeholder: 'Search markets (e.g. Kimironko)...',
    markets_explore_button: 'Explore Market',
    vendors_count: 'Vendors',
    market_purchase: 'Market Purchase',
    verified_buyer: 'Verified Buyer',
    great_marketplace: 'Great marketplace!',
    no_markets_found: 'No markets found yet. Be the first to join!',
    market_not_found: 'Market not found',
    exit_map: 'Exit Map',
    view_full_map: 'View Full Map',
    live_fleet: 'Live Delivery Fleet',
    riders_near: 'Riders near',
    filters: 'Filters',
    search: 'Search',
    price_min: 'Min Price',
    price_max: 'Max Price',
    categories_title: 'Categories',
    all_products: 'All Products',
    hot_deals: 'Hot Deals at',
    community_feedback: 'Community Feedback for',
    no_reviews_yet: 'No reviews yet for this market.',
    no_products_found: 'No products found matching your criteria.',
    // Login / Register
    login_title: 'Welcome Back',
    login_subtitle: 'Sign in to access your orders and account.',
    login_signin: 'Sign In',
    login_signing_in: 'Signing in...',
    login_have_account: 'Already have an account?',
    login_no_account: "Don't have an account?",
    login_register: 'Register',
    login_password: 'Password',
    login_email: 'Email Address',
    login_google: 'Continue with Google',
    continue_google: 'Continue with Google',
    full_name: 'Full Name',
    email_label: 'Email Address',
    password_label: 'Password',
    phone_number: 'Phone Number',
    confirm_password: 'Confirm Password',
    register_title: 'Create an Account',
    register_subtitle: 'Join Rwanda\'s fastest growing marketplace.',
    create_account: 'Create an Account',
    join_marketplace: 'Join Rwanda\'s fastest growing marketplace.',
    i_want_to_be: 'I want to be a:',
    referral_code: 'Referral Code (Optional)',
    creating_account: 'Creating Account...',
    already_have_account: 'Already have an account?',
    sign_in: 'Sign In',
    signing_in: 'Signing in...',
    // Auth Identity Panels
    auth_join_infrastructure: 'Join Rwanda\'s Marketplace.',
    auth_infrastructure_desc: '"Connect with local artisans and sellers across Rwanda. Shop authentic products and get them delivered to your door."',
    auth_access_core: 'Welcome Back.',
    auth_core_desc: '"Connecting buyers with Rwanda\'s best local sellers — secure, fast, and trusted."',
    auth_identity_portal: 'Sign In',
    auth_network_registry: 'Create Account',
    auth_compliance_protocol: 'Verified Platform',
    auth_compliance_desc: 'All sellers are verified with valid business registration before going live on the platform.',
    auth_system_status: 'Platform Status',
    auth_gateway_nominal: 'All Systems Online',
    auth_registry_id: 'Platform ID',
    auth_external_protocols: 'Or continue with',
    auth_required: 'Required',
    auth_secure_mask: 'Private',
    auth_official_name: 'Your full name',
    auth_secure_email: 'Email address',
    auth_optional: 'Optional',
    auth_acquisitions: 'Shop & Buy',
    auth_merchant: 'Sell Products',
    auth_logistics: 'Deliver Orders',
    // Footer
    footer_terms: 'Terms',
    footer_privacy: 'Privacy',
    footer_copy: '© 2026 Rwandan Market Facilitator',
    // Receipt & Chat
    receipt_title: 'Official Receipt',
    receipt_buyer: 'Buyer',
    receipt_seller: 'Seller',
    receipt_products_ordered: 'Products Ordered',
    receipt_payment_summary: 'Payment Summary',
    receipt_total_paid: 'Total Paid',
    receipt_official_digital: 'Official Digital Receipt',
    receipt_close: 'Close Receipt',
    receipt_negotiation_hub: 'Negotiation Hub',
    receipt_view_items: 'View Items',
    chat_active_negotiation: 'Active Negotiation',
    chat_order_in_progress: 'Order in Progress',
    chat_set_location: 'Set Your Delivery Location',
    chat_location_subtitle: 'Search or tap the map to drop your pin',
    chat_confirm_location: 'Confirm Location',
    chat_official_quote: 'Official Quote',
    chat_counter_offer: 'Counter Offer',
    chat_send_quote: 'Send Official Quote',
    chat_type_message: 'Type a message...',
    // Tracking
    track_title: 'Track Order',
    track_not_found: 'Order not found',
    track_negotiation: 'Negotiation with Seller',
    track_package_arrived: 'Package Arrived!',
    track_inspect_goods: 'The rider has arrived. Please inspect your goods and click the button below to confirm you have received everything in good condition.',
    track_rider_heading: 'Rider heading to store',
    track_realtime: 'Track your rider in real-time',
    track_issue: 'Issue with your order?',
    track_confirm_receipt: 'Confirm Receipt (Release Payout)',
    track_dispute_desc: 'If items are missing or damaged, you can raise a dispute within 24 hours.',
    track_submit_dispute: 'Submit Dispute',
    track_dispute_raised: 'Dispute raised. Our team is investigating.',
    track_no_messages: 'No messages yet. Contact the rider if needed.',
    track_rider_handover: 'Rider at store (Handover)',
    track_rider_picked_up: 'Rider has picked up your order!',
    track_rider_en_route: 'The rider is on their way to pick up your items.',
    track_rider_verifying: 'The rider is currently verifying the items at the store.',
    track_assigning_rider: 'Assigning a rider...',
    track_processing: 'Processing Order',
    track_packing: 'The seller is currently packing your items.',
    track_finding_rider: 'Finding the nearest available rider...',
    track_wait_packing: 'Wait while your items are being carefully packed.',
    track_wait_rider: 'Waiting for a rider to accept the delivery.',
    track_delivered: 'Order Delivered!',
    track_placed: 'Order Placed',
    track_enjoy: 'Enjoy your fresh products from the market.',
    track_payment_success: 'Payment successful. Waiting for seller confirmation.',
    track_dispute_placeholder: 'Please describe the issue (e.g. Missing 2kg of tomatoes)',
    track_dispute_error: 'Please provide a reason for the dispute',
    track_dispute_success: 'Dispute raised successfully',
    track_dispute_failed: 'Failed to raise dispute',
    payment_released_thanks: 'Thank you! Payment has been released.',
    confirm_receipt_failed: 'Failed to confirm receipt',
    // Notifications
    notif_new: 'New notification!',
    notif_title: 'Notifications',
    notif_mark_all_read: 'Mark all as read',
    notif_empty: 'No notifications yet.',
    notif_view_all: 'View all activity',
    // Checkout
    checkout_title: 'Checkout',
    checkout_delivery_location: '1. Delivery Location',
    checkout_pinned: 'Pinned',
    checkout_payment_method: '2. Payment Method',
    checkout_momo_number: 'Mobile Money Number',
    checkout_kyc_title: 'KYC Verification (NID Required)',
    checkout_kyc_desc: 'Orders exceeding 50,000 RWF require a National ID for platform security.',
    checkout_notes: 'Delivery Notes / Special Instructions',
    checkout_notes_placeholder: 'e.g. Please bring change for 5000, or call me at the blue gate...',
    checkout_schedule_title: '3. Delivery Schedule',
    checkout_recurring: 'Enable Recurring Delivery',
    checkout_frequency: 'Frequency',
    checkout_every_week: 'Every Week',
    checkout_every_month: 'Every Month',
    checkout_delivery_day: 'Delivery Day',
    checkout_schedule_desc: 'Your first delivery will be processed immediately. Subsequent deliveries will be auto-generated on your selected day.',
    checkout_onetime_selected: 'Standard one-time delivery selected.',
    checkout_summary: 'Order Summary',
    checkout_fee: 'Delivery Fee',
    checkout_out_of_range: 'Out of Delivery Range (Max 15km)',
    checkout_select_location: 'Select location',
    checkout_gateway_fee: 'Gateway Fee (2%)',
    checkout_awaiting_approval: 'Awaiting Payment Approval...',
    checkout_pay_place: 'Pay & Place Order',
    checkout_ussd_info: 'No internet? Dial *182# to complete your order via USSD.',
    checkout_moving_forward: 'Order moving forward!',
    checkout_cart_empty: 'Your cart is empty!',
    checkout_drop_pin: 'Please drop a pin for your delivery location.',
    checkout_enter_phone: 'Please enter your mobile money number.',
    checkout_nid_required: 'National ID is required for orders above 50,000 RWF (KYC Lite).',
    checkout_invalid_cart: 'Invalid cart: missing seller information.',
    checkout_payment_received: 'Payment received! Order confirmed.',
    checkout_check_phone: 'Please check your phone to approve the payment prompt.',
    checkout_failed_for: 'Order(s) failed for',
    checkout_failed_general: 'Failed to place order. Please try again.',
    // Layout
    lang_en: 'English',
    lang_fr: 'French',
    lang_kin: 'Ikinyarwanda',
    change_language: 'Change Language',
    // Days
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    // Terms & Privacy
    terms_title: 'Terms of Service',
    terms_last_updated: 'Last updated: May 3, 2026',
    terms_1_title: '1. Acceptance of Terms',
    terms_1_desc: 'By accessing and using Rwanda Market Facilitator, you agree to be bound by these Terms of Service.',
    terms_2_title: '2. Description of Service',
    terms_2_desc: 'We provide a digital marketplace connecting Rwandan physical markets with online buyers and delivery riders.',
    terms_3_title: '3. User Responsibilities',
    terms_3_desc: 'Users must provide accurate information and comply with Rwandan e-commerce laws.',
    terms_4_title: '4. Payments',
    terms_4_desc: 'Payments are handled via integrated mobile money services. Commissions are automatically deducted.',
    privacy_title: 'Privacy Policy',
    privacy_last_updated: 'Last updated: May 3, 2026',
    privacy_intro: 'Your privacy is important to us. This policy explains how we collect and use your data.',
    privacy_1_title: '1. Data Collection',
    privacy_1_desc: 'We collect location data for delivery tracking and contact information for order fulfillment.',
    privacy_2_title: '2. Data Usage',
    privacy_2_desc: 'Your data is used solely to provide the marketplace services and improve user experience.',
    privacy_3_title: '3. Third-Party Sharing',
    privacy_3_desc: 'We only share necessary data with riders and payment providers to complete your orders.',
  },
  fr: {
    // General
    cancel: 'Annuler',
    loading: 'Chargement...',
    save: 'Enregistrer',
    success: 'Succès !',
    error: 'Une erreur est survenue',
    items: 'articles',
    product: 'Produit',
    // Nav
    nav_login: 'Se Connecter',
    nav_markets: 'Marchés',
    nav_cart: 'Panier',
    nav_wishlist: 'Favoris',
    nav_my_orders: 'Mes Commandes',
    site_name: 'Facilitateur du Marché Rwandais',
    nav_terms: 'Conditions',
    nav_privacy: 'Confidentialité',
    nav_hub: 'Le Hub',
    nav_artifacts: 'Artéfacts',
    nav_mandates: 'Mandats',
    nav_sign_in: 'Se Connecter',
    nav_join: 'Rejoindre RMF',
    // General Artisan
    official_facilitator: 'Facilitateur Officiel du Marché',
    official_infrastructure: 'Infrastructure Officielle',
    regional_hubs: 'Hubs Régionaux',
    heritage_artifacts: 'Artéfacts du Patrimoine',
    heritage_discovery: 'Découverte du Patrimoine',
    trending_region: 'Tendances dans la Région',
    new_standards: 'Les Nouveaux Standards',
    verified_facility: 'Installation Vérifiée',
    active_facilitators: 'Facilitateurs Actifs',
    creative_partners: 'Partenaires Créatifs',
    secure_transit: 'Transit Sécurisé',
    citizen_approval: 'Approbation Citoyenne',
    commercial_fulfillment: 'Exécution Commerciale',
    mandate_id: 'ID du Mandat',
    lifecycle_stage: 'Étape du Cycle de Vie',
    review_mandate: 'Réviser le Mandat',
    refine_discovery: 'Affiner la Découverte',
    find_hub_placeholder: 'Trouver un hub...',
    no_hubs_deployed: 'Aucun hub actuellement déployé dans le réseau',
    secure_hubs_title: 'Hubs Commerciaux Rwandais Sécurisés',
    secure_hubs_desc: '"Chaque hub du réseau RMF fonctionne selon des normes de facilitation strictes, garantissant une sécurité de niveau institutionnel pour vos acquisitions."',
    verified_partner: 'Partenaire Vérifié',
    network_reach: 'Portée du Réseau',
    acquisitions: 'Acquisitions',
    facilitator_support: 'Support Facilitateur',
    // Detail Pages
    accessing_market_hub: 'Accès au Hub du Marché...',
    unveiling_heritage_artifact: 'Dévoilement de l\'Artéfact du Patrimoine...',
    verified_facilitation_hub: 'Hub de Facilitation Vérifié',
    live_fleet_deployment: 'Déploiement de la Flotte en Direct',
    facilitators_active_near: 'Facilitateurs actuellement actifs près de',
    expand_logistics_view: 'Agrandir la Vue Logistique',
    close_tactical_view: 'Fermer la Vue Tactique',
    search_collection: 'Rechercher dans la collection...',
    all_artifacts: 'Tous les Artéfacts',
    the_collection: 'La Collection',
    quality_assurance: 'Assurance Qualité',
    customer_experience: 'Expérience Client',
    master_artisan: 'Maître Artisan',
    crafted_on_commission: 'Fabriqué sur Commission',
    in_facility_storage: 'En Stockage d\'Installation',
    facilitation_brief: 'Brief de Facilitation',
    save_to_heritage_list: 'Enregistrer dans la Liste du Patrimoine',
    global_rating: 'Note Globale',
    items_found: 'Articles Trouvés',
    // Home
    home_hero_title: 'Hubs Institutionnels du Rwanda,\nFacilitation Professionnelle',
    home_hero_desc: 'Découvrez le patrimoine du Rwanda grâce à notre réseau de facilitation vérifié. Acquisitions sécurisées auprès de maîtres artisans livrées par logistique officielle.',
    home_hero_cta: 'Explorer les Hubs du Réseau',
    home_explore_heading: 'Hubs Régionaux de Facilitation',
    home_search_placeholder: 'Rechercher hubs, artéfacts ou mandats...',
    home_trending_products: 'Artéfacts Tendances',
    home_trending_subtitle: 'Acquisitions les plus actives en ce moment',
    view_all_markets: 'Voir tous les Hubs',
    how_it_works_title: 'Le Flux de Facilitation',
    how_it_works_subtitle: 'Un écosystème fluide connectant acheteurs, marchands vérifiés et flottes logistiques.',
    step_1_title: '1. Déploiement du Mandat',
    step_1_desc: 'Initialisez votre mandat d\'acquisition via notre passerelle numérique sécurisée.',
    step_2_title: '2. Traitement au Hub',
    step_2_desc: 'Des artisans vérifiés préparent vos artéfacts au sein de nos installations régionales.',
    step_3_title: '3. Exécution Logistique',
    step_3_desc: 'La flotte RMF exécute la livraison finale à vos coordonnées précises.',
    trust_title: 'Qualité et Sécurité Institutionnelles',
    trust_point_1_title: 'Protection du Facilitateur',
    trust_point_1_desc: 'Chaque transaction est soutenue par le Fonds de Confiance RMF, garantissant l\'intégrité de l\'artéfact.',
    become_seller: 'Rejoindre le Réseau de Marchands',
    active_sellers: 'Marchands Vérifiés',
    shop_now: 'Initialiser le Mandat',
    verified_sellers_title: 'Artisans Vérifiés',
    verified_sellers_desc: 'Chaque marchand du réseau est audité pour sa qualité et son authenticité.',
    secure_payments_title: 'Règlement Sécurisé',
    secure_payments_desc: 'Vos règlements sont conservés en séquestre jusqu\'à confirmation de la réception.',
    trust_point_2_title: 'Réseau de Vendeurs Vérifiés',
    trust_point_2_desc: 'Nous collaborons uniquement avec des artisans et des marchés respectant les normes les plus strictes de qualité.',
    trust_point_3_title: 'Suivi Logistique en Temps Réel',
    trust_point_3_desc: 'Du hub à votre porte, suivez chaque étape de votre expédition via notre flotte de livreurs dédiée.',
    facilitation_mission_title: 'Faciliter la Prochaine Ère de l\'',
    facilitation_mission_span: 'Artisanat Rwandais.',
    artisan_testimonial: '"RMF a transformé ma façon de joindre mes clients. La facilitation est fluide et digne de confiance."',
    master_weaver_label: 'Maître Tisserand, Hub de Kigali',
    // Product
    product_add_to_cart: 'Ajouter au Panier',
    product_buy_now: 'Acheter Maintenant',
    product_out_of_stock: 'Rupture de Stock',
    product_available: 'Disponible',
    product_price_on_quote: 'Prix sur Devis',
    product_messaging_quote: '📜 Demande de Devis',
    product_send_quote: '📩 Envoyer une Demande de Devis',
    product_by_command: 'Sur Commande',
    product_made_in_rwanda: 'Fabriqué au Rwanda',
    product_off: 'DE RÉDUCTION',
    verified_seller_label: 'Artisan Vérifié',
    // Cart
    cart_title: 'Votre Panier',
    cart_empty: 'Votre panier est vide',
    cart_empty_desc: 'Il semble que vous n\'ayez encore rien ajouté à votre panier.',
    cart_checkout: 'Passer à la Caisse',
    cart_total: 'Total',
    cart_delivery: 'Frais de Livraison',
    cart_subtotal: 'Sous-total',
    cart_estimated_total: 'Total Estimé',
    cart_proceed_checkout: 'Passer à la Caisse',
    cart_calculated_at_checkout: 'Calculé à la caisse',
    start_shopping: 'Commencer mes Achats',
    continue_shopping: 'Continuer mes Achats',
    items_added_to_cart: 'Articles ajoutés au panier !',
    // Wishlist
    wishlist_subtitle: 'Gardez une trace de vos produits locaux préférés.',
    wishlist_empty_title: 'Votre liste de souhaits est vide',
    wishlist_empty_desc: 'Découvrez des produits incroyables des marchés locaux du Rwanda.',
    // Orders
    orders_title: 'Mes Commandes',
    orders_subtitle: 'Consultez l\'historique de vos commandes et suivez les livraisons actives.',
    orders_empty: 'Pas encore de commandes',
    order_summary: 'Résumé de la Commande',
    total_paid: 'Total Payé',
    customer_reviews: 'Avis Clients',
    track_order: 'Suivre la Commande',
    write_review: 'Écrire un Avis',
    submit_review: 'Envoyer l\'Avis',
    order: 'Commande',
    products: 'produit(s)',
    bespoke_item: 'Article sur mesure',
    no_orders_shopping: 'Aucune commande trouvée. Commencez vos achats !',
    receipt: 'Reçu',
    review_title: 'Évaluez votre commande',
    rate_seller: 'Noter le Vendeur',
    rate_rider: 'Noter le Livreur',
    rate_market: 'Noter le Marché',
    rate_item: 'Noter l\'Article',
    seller_review_placeholder: 'Comment était le service et l\'emballage ?',
    rider_review_placeholder: 'La livraison était-elle rapide et professionnelle ?',
    market_review_placeholder: 'Comment était la propreté et la sécurité du marché ?',
    product_review_placeholder: 'Quelle était la qualité de cet article ?',
    submit_all_reviews: 'Envoyer tous les avis',
    reviews_submitted: 'Avis envoyés avec succès !',
    reviews_submit_failed: 'Échec de l\'envoi des avis. Veuillez réessayer.',
    // Order Statuses
    status_pending: 'Paiement en attente',
    status_paid: 'Payé',
    status_PAID: 'Payé',
    status_confirmed: 'Confirmé',
    status_processing: 'Traitement',
    status_packing: 'Emballage',
    status_ready_for_pickup: 'Prêt pour ramassage',
    status_rider_assigned: 'Livreur assigné',
    status_rider_at_store: 'Livreur au magasin',
    status_picked_up: 'Récupéré',
    status_en_route: 'En route',
    status_in_transit: 'En transit',
    status_arrived: 'Arrivé',
    status_delivered: 'Livré',
    status_cancelled: 'Annulé',
    status_disputed: 'Contesté',
    // Dashboard
    dashboard_welcome: 'Bienvenue',
    dashboard_manage: 'Gérez vos commandes et vos paramètres de compte.',
    dashboard_view_all: 'Voir toutes les Commandes',
    dashboard_activity: 'Aperçu de l\'Activité',
    dashboard_orders_placed: 'Commandes Passées',
    dashboard_wishlist_items: 'Articles en Favoris',
    dashboard_platform_activity: 'Activité de la Plateforme',
    dashboard_total_orders: 'Total des Commandes',
    dashboard_in_progress: 'En Cours',
    dashboard_delivered: 'Livré',
    dashboard_ref_earnings: 'Gains Parrainage',
    dashboard_live_tracking: 'Suivi de Livraison en Direct',
    dashboard_recent_history: 'Historique d\'Achat Récent',
    dashboard_view_complete: 'Voir l\'Historique Complet',
    dashboard_no_deliveries: 'Pas de livraison active pour le moment.',
    dashboard_no_deliveries_desc: 'Vos commandes apparaîtront ici une fois qu\'elles seront traitées.',
    dashboard_no_history: 'Aucun historique d\'achat trouvé.',
    dashboard_receipt: 'Reçu',
    dashboard_repeat: 'Répéter',
    dashboard_rate: 'Noter',
    dashboard_rate_purchase: 'Évaluez votre achat',
    dashboard_rate_experience: 'Comment s\'est passée votre expérience avec {seller} ?',
    dashboard_leave_comment: 'Laissez un commentaire (optionnel)',
    dashboard_wallet_balance: 'Mon Solde Portefeuille',
    dashboard_top_up: 'Recharger le Portefeuille',
    dashboard_refer_earn: 'Parrainez et Gagnez',
    dashboard_refer_desc: 'Parrainez des amis et gagnez 1 000 RWF !',
    dashboard_copy_link: 'Copier le lien',
    dashboard_recurring: 'Livraisons Récurrentes',
    dashboard_no_subscriptions: 'Aucun abonnement actif.',
    dashboard_next_delivery: 'Prochaine Livraison',
    dashboard_track_map: 'Suivre sur la Carte',
    transit_terminal: 'Terminal de Transit',
    reliability_rate: 'Taux de Fiabilité',
    service_rating: 'Évaluation du Service',
    verified_facilitator: 'Facilitateur Vérifié',
    total_deliveries: 'Livraisons Totales',
    lifetime_fulfillment: 'Accomplissement à Vie',
    active_mandate: 'Mandat Actif',
    shopper: 'Acheteur',
    seller: 'vendeur',
    buyer: 'acheteur',
    link_copied: 'Lien copié !',
    review_submitted_thanks: 'Merci pour votre retour !',
    review_submit_failed: 'Échec de l\'envoi de l\'avis',
    pause: 'Pause',
    // Markets
    markets_title: "Explorez les Marchés du Rwanda",
    markets_subtitle: 'Parcourez les marchés publics vibrants et les boutiques indépendantes vérifiées. Directement de la source à votre porte.',
    markets_search_placeholder: 'Rechercher des marchés (ex: Kimironko)...',
    markets_explore_button: 'Explorer le Marché',
    vendors_count: 'Vendeurs',
    market_purchase: 'Achat au Marché',
    verified_buyer: 'Acheteur Vérifié',
    great_marketplace: 'Super marché !',
    no_markets_found: 'Aucun marché trouvé pour le moment. Soyez le premier à rejoindre !',
    market_not_found: 'Marché non trouvé',
    exit_map: 'Quitter la Carte',
    view_full_map: 'Voir la Carte Complète',
    live_fleet: 'Flotte de Livraison en Direct',
    riders_near: 'Livreurs près de',
    filters: 'Filtres',
    search: 'Recherche',
    price_min: 'Prix Min',
    price_max: 'Prix Max',
    categories_title: 'Catégories',
    all_products: 'Tous les Produits',
    hot_deals: 'Offres Spéciales à',
    community_feedback: 'Avis de la Communauté pour',
    no_reviews_yet: 'Pas encore d\'avis pour ce marché.',
    no_products_found: 'Aucun produit ne correspond à vos critères.',
    // Login / Register
    login_title: 'Bienvenue',
    login_subtitle: 'Connectez-vous pour accéder à vos commandes.',
    login_signin: 'Se Connecter',
    login_signing_in: 'Connexion...',
    login_have_account: 'Déjà un compte ?',
    login_no_account: "Pas encore de compte ?",
    login_register: "S'inscrire",
    login_password: 'Mot de Passe',
    login_email: 'Adresse Email',
    login_google: 'Continuer avec Google',
    continue_google: 'Continuer avec Google',
    full_name: 'Nom Complet',
    email_label: 'Adresse Email',
    password_label: 'Mot de Passe',
    phone_number: 'Téléphone',
    confirm_password: 'Confirmer le mot de passe',
    register_title: 'Créer un Compte',
    register_subtitle: 'Rejoignez le marché à la croissance la plus rapide du Rwanda.',
    create_account: 'Créer un Compte',
    join_marketplace: 'Rejoignez le marché à la croissance la plus rapide du Rwanda.',
    i_want_to_be: 'Je veux être un :',
    referral_code: 'Code de Parrainage (Optionnel)',
    creating_account: 'Création du compte...',
    already_have_account: 'Déjà un compte ?',
    sign_in: 'Se Connecter',
    signing_in: 'Connexion...',
    // Auth Identity Panels
    auth_join_infrastructure: 'Rejoindre l\'Infrastructure.',
    auth_infrastructure_desc: '"En vous inscrivant, vous entrez officiellement dans le réseau du Marché Rwandais—un écosystème sécurisé pour les échanges artisanaux haut de gamme."',
    auth_access_core: 'Accéder au Cœur du Réseau.',
    auth_core_desc: '"Sécuriser le patrimoine du Rwanda grâce à une facilitation de marché professionnelle et des normes institutionnelles."',
    auth_identity_portal: 'Portail d\'Identité',
    auth_network_registry: 'Registre du Réseau',
    auth_compliance_protocol: 'Protocole de Conformité',
    auth_compliance_desc: 'Tous les comptes subissent une vérification institutionnelle pour maintenir l\'intégrité des hubs régionaux.',
    auth_system_status: 'Statut du Système',
    auth_gateway_nominal: 'Passerelle Nominale',
    auth_registry_id: 'ID de Registre',
    auth_external_protocols: 'Protocoles Externes',
    auth_required: 'REQUIS',
    auth_secure_mask: 'MASQUE SÉCURISÉ',
    auth_official_name: 'NOM LÉGAL OFFICIEL',
    auth_secure_email: 'EMAIL SÉCURISÉ',
    auth_optional: 'OPTIONNEL',
    auth_acquisitions: 'Acquisitions',
    auth_merchant: 'Marchand',
    auth_logistics: 'Logistique',
    // Footer
    footer_terms: 'Conditions',
    footer_privacy: 'Confidentialité',
    footer_copy: '© 2026 Rwandan Market Facilitator',
    // Receipt & Chat
    receipt_title: 'Reçu Officiel',
    receipt_buyer: 'Acheteur',
    receipt_seller: 'Vendeur',
    receipt_products_ordered: 'Produits Commandés',
    receipt_payment_summary: 'Résumé du Paiement',
    receipt_total_paid: 'Total Payé',
    receipt_official_digital: 'Reçu Numérique Officiel',
    receipt_close: 'Fermer le Reçu',
    receipt_negotiation_hub: 'Centre de Négociation',
    receipt_view_items: 'Voir les Articles',
    chat_active_negotiation: 'Négociation Active',
    chat_order_in_progress: 'Commande en Cours',
    chat_set_location: 'Définir votre Lieu de Livraison',
    chat_location_subtitle: 'Cherchez ou tapez sur la carte',
    chat_confirm_location: 'Confirmer le Lieu',
    chat_official_quote: 'Devis Officiel',
    chat_counter_offer: 'Contre-Offre',
    chat_send_quote: 'Envoyer le Devis',
    chat_type_message: 'Écrire un message...',
    // Tracking
    track_title: 'Suivre la Commande',
    track_not_found: 'Commande non trouvée',
    track_negotiation: 'Négociation avec le Vendeur',
    track_package_arrived: 'Colis Arrivé !',
    track_inspect_goods: 'Le livreur est arrivé. Veuillez inspecter vos marchandises et cliquer sur le bouton ci-dessous pour confirmer que vous avez tout reçu en bon état.',
    track_rider_heading: 'Le livreur se rend au magasin',
    track_realtime: 'Suivez votre livreur en temps réel',
    track_issue: 'Un problème avec votre commande ?',
    track_confirm_receipt: 'Confirmer la Réception (Libérer le Paiement)',
    track_dispute_desc: 'Si des articles sont manquants ou endommagés, vous pouvez ouvrir un litige dans les 24 heures.',
    track_submit_dispute: 'Soumettre un Litige',
    track_dispute_raised: 'Litige ouvert. Notre équipe enquête.',
    track_no_messages: 'Aucun message pour l\'instant. Contactez le livreur si besoin.',
    track_rider_handover: 'Livreur au magasin (Remise)',
    track_rider_picked_up: 'Le livreur a récupéré votre commande !',
    track_rider_en_route: 'Le livreur est en route pour récupérer vos articles.',
    track_rider_verifying: 'Le livreur vérifie actuellement les articles au magasin.',
    track_assigning_rider: 'Assignation d\'un livreur...',
    track_processing: 'Traitement de la commande',
    track_packing: 'Le vendeur emballe actuellement vos articles.',
    track_finding_rider: 'Recherche du livreur le plus proche...',
    track_wait_packing: 'Veuillez patienter pendant que vos articles sont emballés avec soin.',
    track_wait_rider: 'En attente qu\'un livreur accepte la livraison.',
    track_delivered: 'Commande Livrée !',
    track_placed: 'Commande Passée',
    track_enjoy: 'Profitez de vos produits frais du marché.',
    track_payment_success: 'Paiement réussi. En attente de la confirmation du vendeur.',
    track_dispute_placeholder: 'Veuillez décrire le problème (ex: Manque 2kg de tomates)',
    track_dispute_error: 'Veuillez fournir un motif pour le litige',
    track_dispute_success: 'Litige ouvert avec succès',
    track_dispute_failed: 'Échec de l\'ouverture du litige',
    payment_released_thanks: 'Merci ! Le paiement a été libéré.',
    confirm_receipt_failed: 'Échec de la confirmation de réception',
    // Notifications
    notif_new: 'Nouvelle notification !',
    notif_title: 'Notifications',
    notif_mark_all_read: 'Tout marquer comme lu',
    notif_empty: 'Aucune notification pour l\'instant.',
    notif_view_all: 'Voir toute l\'activité',
    // Checkout
    checkout_title: 'Caisse',
    checkout_delivery_location: '1. Lieu de Livraison',
    checkout_pinned: 'Épinglé',
    checkout_payment_method: '2. Mode de Paiement',
    checkout_momo_number: 'Numéro Mobile Money',
    checkout_kyc_title: 'Vérification KYC (NID Requis)',
    checkout_kyc_desc: 'Les commandes de plus de 50 000 RWF nécessitent une carte d\'identité pour la sécurité.',
    checkout_notes: 'Notes de Livraison / Instructions Spéciales',
    checkout_notes_placeholder: 'ex: Apportez de la monnaie pour 5000, ou appelez-moi au portail bleu...',
    checkout_schedule_title: '3. Calendrier de Livraison',
    checkout_recurring: 'Activer la Livraison Récurrente',
    checkout_frequency: 'Fréquence',
    checkout_every_week: 'Chaque Semaine',
    checkout_every_month: 'Chaque Mois',
    checkout_delivery_day: 'Jour de Livraison',
    checkout_schedule_desc: 'Votre première livraison sera traitée immédiatement. Les livraisons suivantes seront générées automatiquement.',
    checkout_onetime_selected: 'Livraison standard unique sélectionnée.',
    checkout_summary: 'Résumé de la Commande',
    checkout_fee: 'Frais de Livraison',
    checkout_out_of_range: 'Hors zone de livraison (Max 15km)',
    checkout_select_location: 'Sélectionnez un lieu',
    checkout_gateway_fee: 'Frais de Passerelle (2%)',
    checkout_awaiting_approval: 'En attente d\'approbation du paiement...',
    checkout_pay_place: 'Payer & Commander',
    checkout_ussd_info: 'Pas d\'internet ? Composez le *182# pour commander via USSD.',
    checkout_moving_forward: 'La commande avance !',
    checkout_cart_empty: 'Votre panier est vide !',
    checkout_drop_pin: 'Veuillez épingler votre lieu de livraison.',
    checkout_enter_phone: 'Veuillez entrer votre numéro mobile money.',
    checkout_nid_required: 'La carte d\'identité est requise pour les commandes de plus de 50 000 RWF.',
    checkout_invalid_cart: 'Panier invalide : informations vendeur manquantes.',
    checkout_payment_received: 'Paiement reçu ! Commande confirmée.',
    checkout_check_phone: 'Veuillez vérifier votre téléphone pour approuver le paiement.',
    checkout_failed_for: 'Échec de la commande pour',
    checkout_failed_general: 'Échec de la commande. Veuillez réessayer.',
    // Layout
    lang_en: 'Anglais',
    lang_fr: 'Français',
    lang_kin: 'Ikinyarwanda',
    change_language: 'Changer la langue',
    // Days
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
    // Terms & Privacy
    terms_title: 'Conditions d\'Utilisation',
    terms_last_updated: 'Dernière mise à jour : 3 mai 2026',
    terms_1_title: '1. Acceptation des Conditions',
    terms_1_desc: 'En accédant et en utilisant Rwandan Market Facilitator, vous acceptez d\'être lié par ces Conditions d\'Utilisation.',
    terms_2_title: '2. Description du Service',
    terms_2_desc: 'Nous fournissons une plateforme numérique connectant les marchés physiques rwandais avec des acheteurs en ligne et des livreurs.',
    terms_3_title: '3. Responsabilités de l\'Utilisateur',
    terms_3_desc: 'Les utilisateurs doivent fournir des informations exactes et se conformer aux lois rwandaises sur le commerce électronique.',
    terms_4_title: '4. Paiements',
    terms_4_desc: 'Les paiements sont gérés via des services de mobile money intégrés. Les commissions sont automatiquement déduites.',
    privacy_title: 'Politique de Confidentialité',
    privacy_last_updated: 'Dernière mise à jour : 3 mai 2026',
    privacy_intro: 'Votre vie privée est importante pour nous. Cette politique explique comment nous collectons et utilisons vos données.',
    privacy_1_title: '1. Collecte de Données',
    privacy_1_desc: 'Nous collectons des données de localisation pour le suivi des livraisons et des informations de contact pour l\'exécution des commandes.',
    privacy_2_title: '2. Utilisation des Données',
    privacy_2_desc: 'Vos données sont utilisées uniquement pour fournir les services de la plateforme et améliorer l\'expérience utilisateur.',
    privacy_3_title: '3. Partage avec des Tiers',
    privacy_3_desc: 'Nous ne partageons que les données nécessaires avec les livreurs et les prestataires de paiement pour finaliser vos commandes.',
  },
  kin: {
    // General
    cancel: 'Hagarika',
    loading: 'Birategurwa...',
    save: 'Bika',
    success: 'Byagenze neza!',
    error: 'Hari ikibazo cyabaye',
    items: 'ibintu',
    product: 'Igicuruzwa',
    // Nav
    nav_login: 'Injira',
    nav_markets: 'Amasoko',
    nav_cart: 'Agashashi',
    nav_wishlist: 'Ibirindwa',
    nav_my_orders: 'Ibyangombwa Byanjye',
    site_name: 'Umutunganyiriza w\'Amasoko y\'u Rwanda',
    nav_terms: 'Amategeko',
    nav_privacy: 'Ibijyanye n\'ibanga',
    nav_hub: 'Icyicaro',
    nav_artifacts: 'Ibihangano',
    nav_mandates: 'Ubusabe',
    nav_sign_in: 'Injira',
    nav_join: 'Fatanya na RMF',
    // General Artisan
    official_facilitator: 'Umutunganyiriza w\'Isoko mu Buryo bwemewe',
    official_infrastructure: 'Inzego z\'Ireme z\'Igihugu',
    regional_hubs: 'Ibyicaro by\'Akarere',
    heritage_artifacts: 'Ibihangano n\'Umurage',
    heritage_discovery: 'Gushakisha Umurage',
    trending_region: 'Ibirimo gukundwa mu gace',
    new_standards: 'Ibisigaye bishya',
    verified_facility: 'Icyicaro Cyemejwe',
    active_facilitators: 'Abakozi Bakora',
    creative_partners: 'Abafatanyabikorwa b\'Abahanga',
    secure_transit: 'Ubwikorezi bwizewe',
    citizen_approval: 'Ubwemerere bw\'Abaturage',
    commercial_fulfillment: 'Irangizwa ry\'Ubucuruzi',
    mandate_id: 'Inomero y\'Ubusabe',
    lifecycle_stage: 'Ikiciro cy\'Ubuzima',
    review_mandate: 'Subiramo Ubusabe',
    refine_discovery: 'Nonsora Ishakisha',
    find_hub_placeholder: 'Shaka icyicaro...',
    no_hubs_deployed: 'Nta byicaro birashyirwa mu muyoboro ubu',
    secure_hubs_title: 'Ibyicaro by\'Ubucuruzi by\'u Rwanda Byizewe',
    secure_hubs_desc: '"Buri cyicaro mu muyoboro wa RMF gukora ku rwego rwo hejuru, cyizeza umutekano usesuye ku byo mwahashye."',
    verified_partner: 'Umufatanyabikorwa Wemejwe',
    network_reach: 'Imyanzuro y\'Umuyoboro',
    acquisitions: 'Ibyaguzwe',
    facilitator_support: 'Ubufasha bw\'Umutunganyiriza',
    // Detail Pages
    accessing_market_hub: 'Kwinjira mu Cyicaro cy\'Isoko...',
    unveiling_heritage_artifact: 'Kwerekana Igihangano cy\'Umurage...',
    verified_facilitation_hub: 'Icyicaro cy\'Ubufasha Cyemejwe',
    live_fleet_deployment: 'Itsinda ry\'Abatwara riri gukora',
    facilitators_active_near: 'Abatwara bari hafi ya',
    expand_logistics_view: 'Agura Igaragara ry\'Ubwikorezi',
    close_tactical_view: 'Funga Igaragara ry\'Ubwikorezi',
    search_collection: 'Shakisha mu bihangano...',
    all_artifacts: 'Ibihangano Byose',
    the_collection: 'Ibyatoranyijwe',
    quality_assurance: 'Ireme Ryizewe',
    customer_experience: 'Uko abaguzi babyakiriye',
    master_artisan: 'Umuhanzi w\'Indashyikirwa',
    crafted_on_commission: 'Bikorerwa ku Bumbatira',
    in_facility_storage: 'Bibitse mu Cyicaro',
    facilitation_brief: 'Incamake y\'Ishyirwa mu Bikora',
    save_to_heritage_list: 'Bika mu Birindwa by\'Umurage',
    global_rating: 'Ireme rusange',
    items_found: 'Ibibonetse',
    // Home
    home_hero_title: 'Ibyicaro by\'Isoko by\'u Rwanda,\nUbufasha bwa Kinyamwuga',
    home_hero_desc: 'Shakisha umurage w\'u Rwanda binyuze mu muyoboro wacu wemejwe. Gura ibihangano byizewe bitunganyirizwa mu buryo bwemewe.',
    home_hero_cta: 'Shakisha Ibyicaro by\'Umuyoboro',
    home_explore_heading: 'Ibyicaro by\'Ubufasha by\'Akarere',
    home_search_placeholder: 'Shakisha ibyicaro, ibihangano, cyangwa ubusabe...',
    home_trending_products: 'Ibihangano Bikunzwe',
    home_trending_subtitle: 'Ibyaguzwe cyane muri uyu mwanya',
    view_all_markets: 'Reba Ibyicaro Yose',
    how_it_works_title: 'Uburyo bwo Gufasha',
    how_it_works_subtitle: 'Uburyo bworoshye buhuza abaguzi, abacuruzi bemejwe, n\'abatanga serivisi.',
    step_1_title: '1. Gutangiza Ubusabe',
    step_1_desc: 'Tangiza ubusabe bwawe binyuze mu muyoboro wacu wizewe.',
    step_2_title: '2. Gutunganyirizwa mu Cyicaro',
    step_2_desc: 'Abahanzi bemejwe bategura ibyo waguze mu byicaro byacu by\'akarere.',
    step_3_title: '3. Kurangiza Ubwikorezi',
    step_3_desc: 'Itsinda rya RMF rirangiza itangwa ry\'ibyo waguze aho uherereye neza.',
    trust_title: 'Ireme n\'Umutekano by\'Urwego rwo Hejuru',
    trust_point_1_title: 'Kurinda Umukoresha',
    trust_point_1_desc: 'Buri gikorwa cyose gishyigikiwe n\'ikigega cya RMF cyizeza ireme rishitse.',
    become_seller: 'Injira mu Muyoboro w\'Abacuruzi',
    active_sellers: 'Abacuruzi Bemejwe',
    shop_now: 'Tangiza Ubusabe',
    verified_sellers_title: 'Abahanzi Bemejwe',
    verified_sellers_desc: 'Buri mucuruzi mu muyoboro asuzumwa ireme n\'umwimerere w\'ibyo akora.',
    secure_payments_title: 'Ubwishyu bwizewe',
    secure_payments_desc: 'Ubwishyu bwawe bubikwa neza kugeza wemeje ko wakiriye ibyo waguze.',
    trust_point_2_title: 'Umuyoboro w\'Abagurisha Bemejwe',
    trust_point_2_desc: 'Dukorana gusa n\'abahanzi n\'amasoko yubaha amabwiriza y\'ireme n\'umwimerere.',
    trust_point_3_title: 'Gukurikirana Ubwikorezi mu Mvugo ya None',
    trust_point_3_desc: 'Kuva mu cyicaro kugeza ku rugo rwawe, kurikirana buri ntambwe y\'urugendo rw\'ibyo waguze.',
    facilitation_mission_title: 'Gufasha Igihe Gishya cy\'',
    facilitation_mission_span: 'Ubuhanzi bw\'u Rwanda.',
    artisan_testimonial: '"RMF yahinduye uburyo ngera ku bakiriya banjye. Ubufasha bwayo burizewe kandi burashitse."',
    master_weaver_label: 'Umuhanzi w\'Indashyikirwa, Kigali Hub',
    // Product
    product_add_to_cart: 'Shyira mu Gashatsi',
    product_buy_now: 'Gura Nonaha',
    product_out_of_stock: 'Nta Rukurikirane',
    product_available: 'Biraboneka',
    product_price_on_quote: 'Igiciro Kizavugwa',
    product_messaging_quote: '📜 Saba Igiciro',
    product_send_quote: '📩 Ohereza Ikibazo cy\'Igiciro',
    product_by_command: 'Ku Itegeko',
    product_made_in_rwanda: 'Byakorewe mu Rwanda',
    product_off: 'YAGABANYIJWE',
    verified_seller_label: 'Umuhanzi Wemejwe',
    // Cart
    cart_title: 'Agashashi Kawe',
    cart_empty: 'Agashashi kawe kera ubusa',
    cart_empty_desc: 'Urabona ko nta kintu na kimwe urashyira mu mufuka wawe.',
    cart_checkout: 'Komeza Kwishyura',
    cart_total: 'Igiteranyo',
    cart_delivery: 'Amafaranga yo Gutanga',
    cart_subtotal: 'Igice cy\'igiciro',
    cart_estimated_total: 'Igiteranyo kigenekereje',
    cart_proceed_checkout: 'Komeza Wishyure',
    cart_calculated_at_checkout: 'Bizaboneka wishyura',
    start_shopping: 'Tangira Guhahira',
    continue_shopping: 'Komeza Guhaha',
    items_added_to_cart: 'Ibicuruzwa byashyizwe mu gashashi!',
    // Wishlist
    wishlist_subtitle: 'Kurikirana ibicuruzwa byawe ukunda.',
    wishlist_empty_title: 'Agashashi k\'Ibirindwa kera ubusa',
    wishlist_empty_desc: 'Shakisha ibicuruzwa bitangaje mu masoko y\'u Rwanda.',
    // Orders
    orders_title: 'Ibyangombwa Byanjye',
    orders_subtitle: 'Reba amateka y\'ibyo waguze kandi ukurikire aho biri ubu.',
    orders_empty: 'Nta byangombwa bihari',
    order_summary: 'Incamake y\'Ibyatunzwe',
    total_paid: 'Igiteranyo Cyishyuwe',
    customer_reviews: 'Ibitekerezo by\'Abaguzi',
    track_order: 'Kurikirana Ibyo Wagurishije',
    write_review: 'Andika Igitekerezo',
    submit_review: 'Ohereza Igitekerezo',
    order: 'Icyatunzwe',
    products: 'igicuruzwa',
    bespoke_item: 'Igikoresho cyihariye',
    no_orders_shopping: 'Nta byo waguze biraboneka. Tangira guhaha!',
    receipt: 'Inyemezabwishyu',
    review_title: 'Andika uko ubusabe bwawe bwagenze',
    rate_seller: 'Vuga uko Umugurisha yakoze',
    rate_rider: 'Vuga uko Umutwara yakoze',
    rate_market: 'Vuga uko Isoko rimeze',
    rate_item: 'Vuga uko Igicuruzwa kimeze',
    seller_review_placeholder: 'Serivisi n\'imipakire byari bimeze bite?',
    rider_review_placeholder: 'Umutwara yihuse kandi yari afite ikinyabupfura?',
    market_review_placeholder: 'Isoko ryari rifite isuku n\'umutekano?',
    product_review_placeholder: 'Ubwiza bw\'iki gicuruzwa bwari bumeze bite?',
    submit_all_reviews: 'Ohereza ibitekerezo byose',
    reviews_submitted: 'Ibitekerezo byoherejwe neza!',
    reviews_submit_failed: 'Guhereza ibitekerezo byanze. Ongera ugerageze.',
    // Order Statuses
    status_pending: 'Gutegereza Ubwishyu',
    status_paid: 'Byishyuwe',
    status_PAID: 'Byishyuwe',
    status_confirmed: 'Byemejwe',
    status_processing: 'Birimo Gutunganywa',
    status_packing: 'Birimo Gupakirwa',
    status_ready_for_pickup: 'Byiteguye Gufatwa',
    status_rider_assigned: 'Umutwara yabonetse',
    status_rider_at_store: 'Umutwara ari ku iduka',
    status_picked_up: 'Byafashwe',
    status_en_route: 'Mu nzira',
    status_in_transit: 'Mu nzira',
    status_arrived: 'Byageze',
    status_delivered: 'Byageze',
    status_cancelled: 'Byasheshwe',
    status_disputed: 'Bifite ikibazo',
    // Dashboard
    dashboard_welcome: 'Murakaza neza',
    dashboard_manage: 'Icunga ibyo watunze n\'imiterere ya konti yawe.',
    dashboard_view_all: 'Reba Ibyatunzwe Byose',
    dashboard_activity: 'Incamake y\'Ibikora',
    dashboard_orders_placed: 'Ibyatunzwe',
    dashboard_wishlist_items: 'Ibyo Wifuza',
    dashboard_platform_activity: 'Ibikorerwa kuri Platform',
    dashboard_total_orders: 'Ibyatunzwe Yose',
    dashboard_in_progress: 'Birimo Gukorwa',
    dashboard_delivered: 'Byageze',
    dashboard_ref_earnings: 'Inyungu z\'Iyamamazabikorwa',
    dashboard_live_tracking: 'Kurikirana aho Ibyo Waguze Bigeze',
    dashboard_recent_history: 'Ibiheruka Kugurwa',
    dashboard_view_complete: 'Reba Amateka Yose',
    dashboard_no_deliveries: 'Nta bintu birimo gutangwa ubu.',
    dashboard_no_deliveries_desc: 'Ibyo watunze bizagaragara hano bimaze gutunganywa.',
    dashboard_no_history: 'Nta mateka yo kugura aboneka.',
    dashboard_receipt: 'Inyemezabwishyu',
    dashboard_repeat: 'Ongera Ugure',
    dashboard_rate: 'Vuga uko Byari Bimeze',
    dashboard_rate_purchase: 'Vuga uko ibyo waguze bimeze',
    dashboard_rate_experience: 'Urubyiruko rwawe n\'{seller} rwagenze rute?',
    dashboard_leave_comment: 'Andika igitekerezo (niba ubishaka)',
    dashboard_wallet_balance: 'Amafaranga ari kuri konti yanjye',
    dashboard_top_up: 'Shyiraho amafaranga',
    dashboard_refer_earn: 'Hamagara inshuti ubone inyungu',
    dashboard_refer_desc: 'Tumira inshuti maze ubone 1,000 RWF bakoze iyakure yabo ya mbere!',
    dashboard_copy_link: 'Kopa link',
    dashboard_recurring: 'Ibicuruzwa ugezwaho kenshi',
    dashboard_no_subscriptions: 'Nta bintu ugezwaho kenshi bihari.',
    dashboard_next_delivery: 'Igihe utegerejeho ibindi',
    dashboard_track_map: 'Kurikirana ku ikarita',
    transit_terminal: 'Icyicaro cy\'Ubwikorezi',
    reliability_rate: 'Igipimo cy\'Ubwizerwa',
    service_rating: 'Inshuro washimiwe',
    verified_facilitator: 'Umutunganyiriza Wemejwe',
    total_deliveries: 'Ibyatunzwe Yose',
    lifetime_fulfillment: 'Amateka y\'Umutwara',
    active_mandate: 'Ubusabe burimo gukorwa',
    shopper: 'Umuguzi',
    seller: 'umugurisha',
    buyer: 'umuguzi',
    link_copied: 'Link yakopewe!',
    review_submitted_thanks: 'Murakoze ku gitekerezo cyanyu!',
    review_submit_failed: 'Guhereza igitekerezo byanze',
    pause: 'Hagarika gato',
    // Markets
    markets_title: 'Shakisha Amasoko ya Rwanda',
    markets_subtitle: 'Rambagira amasoko ya rubanda n\'amaduka yigenga yemejwe. Kuva aho bituruka kugeza ku rugo rwawe.',
    markets_search_placeholder: 'Shakisha amasoko (urugero: Kimironko)...',
    markets_explore_button: 'Rambagira Iri Soko',
    vendors_count: 'Abagurisha',
    market_purchase: 'Icyaguzwe mu isoko',
    verified_buyer: 'Umuguzi Wemejwe',
    great_marketplace: 'Isoko ryiza cyane!',
    no_markets_found: 'Nta masoko arahagaragara. Ba uwa mbere mu kwifatanya natwe!',
    market_not_found: 'Isoko ntiribonetse',
    exit_map: 'Sohoka ku Ikarita',
    view_full_map: 'Reba Ikarita Yose',
    live_fleet: 'Abatwara ibintu bakora ubu',
    riders_near: 'Abatwara ibintu hafi ya',
    filters: 'Guhungura',
    search: 'Shakisha',
    price_min: 'Igiciro Gito',
    price_max: 'Igiciro Kinini',
    categories_title: 'Ibyiciro',
    all_products: 'Ibicuruzwa Byose',
    hot_deals: 'Ibiciro Byagabanyijwe kuri',
    community_feedback: 'Ibitekerezo bya bagenzi bawe kuri',
    no_reviews_yet: 'Nta gitekerezo kirajya kuri iri soko.',
    no_products_found: 'Nta gicuruzwa namba kibonetse.',
    // Login / Register
    login_title: 'Murakaza Neza',
    login_subtitle: 'Injira kugira ngo ugera ku byo watunze.',
    login_signin: 'Injira',
    login_signing_in: 'Kwinjira...',
    login_have_account: 'Ufite konti umaze?',
    login_no_account: 'Nta konti ufite?',
    login_register: 'Iyandikishe',
    login_password: 'Ijambo ry\'ibanga',
    login_email: 'Imeli',
    login_google: 'Komeza na Google',
    continue_google: 'Komeza na Google',
    full_name: 'Amazina Yose',
    email_label: 'Imeli',
    password_label: 'Ijambo ry\'ibanga',
    phone_number: 'Telefone',
    confirm_password: 'Emeza Ijambo ry\'ibanga',
    register_title: 'Fungura Konti',
    register_subtitle: 'Injira mu isoko ririmo gukura vuba mu Rwanda.',
    create_account: 'Fungura Konti',
    join_marketplace: 'Injira mu isoko ririmo gukura vuba mu Rwanda.',
    i_want_to_be: 'Nshaka kuba:',
    referral_code: 'Kode y\'ubutumire (Niba uhifite)',
    creating_account: 'Turimo gufungura konti...',
    already_have_account: 'Ufite konti umaze?',
    sign_in: 'Injira',
    signing_in: 'Kwinjira...',
    // Auth Identity Panels
    auth_join_infrastructure: 'Injira mu Nzira z\'Ireme.',
    auth_infrastructure_desc: '"Kwiyandikisha bivuze ko winjiye mu muyoboro w\'amasoko y\'u Rwanda—uburyo bwizewe bwo guhana ibihangano by\'indashyikirwa."',
    auth_access_core: 'Injira mu Cyicaro cy\'Umuyoboro.',
    auth_core_desc: '"Kurinda umurage w\'u Rwanda binyuze mu butunganyirize bw\'amasoko bwa kinyamwuga n\'inzego z\'ireme."',
    auth_identity_portal: 'Ihuriro ry\'Umwirondoro',
    auth_network_registry: 'Igitabo cy\'Umuyoboro',
    auth_compliance_protocol: 'Amabwiriza Agenga Ireme',
    auth_compliance_desc: 'Konti zose zisuzumwa n\'inzego zibifitiye ubushobozi kugira ngo ireme ry\'ibyicaro by\'akarere ridasubira inyuma.',
    auth_system_status: 'Imiterere ya Sisitemu',
    auth_gateway_nominal: 'Umuyoboro uri gukora neza',
    auth_registry_id: 'Inomero y\'Igitabo',
    auth_external_protocols: 'Uburyo bwo Hanze',
    auth_required: 'BIRAKENEWE',
    auth_secure_mask: 'IJAMBO RY\'IBANGA RYAHISHWE',
    auth_official_name: 'AMAZINA NYAYO YEMEWE',
    auth_secure_email: 'IMELI YIZEWE',
    auth_optional: 'NIBA UBISHAKA',
    auth_acquisitions: 'Ibyaguzwe',
    auth_merchant: 'Umucuruzi',
    auth_logistics: 'Ubwikorezi',
    // Footer
    footer_terms: 'Amategeko',
    footer_privacy: 'Ibijyanye n\'ibanga',
    footer_copy: '© 2026 Rwandan Market Facilitator',
    // Receipt & Chat
    receipt_title: 'Inyemezabwishyu ya Nyayo',
    receipt_buyer: 'Umuguzi',
    receipt_seller: 'Umugurisha',
    receipt_products_ordered: 'Ibicuruzwa Waguzwe',
    receipt_payment_summary: 'Incamake y\'Ubwishyu',
    receipt_total_paid: 'Igiteranyo Cyishyuwe',
    receipt_official_digital: 'Inyemezabwishyu ya Digitale',
    receipt_close: 'Funga Inyemezabwishyu',
    receipt_negotiation_hub: 'Aho Kuganirira',
    receipt_view_items: 'Reba ibintu',
    chat_active_negotiation: 'Ibiganiro Birimo Gukorwa',
    chat_order_in_progress: 'Ibicuruzwa Birimo Gutegurwa',
    chat_set_location: 'Hitamo aho Batinyira Ibyo Waguye',
    chat_location_subtitle: 'Shakisha cyante ukande ku ikarita',
    chat_confirm_location: 'Emeza aho Utuye',
    chat_official_quote: 'Igiciro cya Nyayo',
    chat_counter_offer: 'Guhangana ku Giciro',
    chat_send_quote: 'Ohereza Igiciro cya Nyayo',
    chat_type_message: 'Andika ubutumwa...',
    // Tracking
    track_title: 'Kurikirana Ibyo Waguze',
    track_not_found: 'Ibyo waguze ntibigaragara',
    track_negotiation: 'Kuganira n\'Umugurisha',
    track_package_arrived: 'Ibyo waguze Byageze!',
    track_inspect_goods: 'Umutwara amaze kuhagera. Reba niba ibyo waguze ari bizima hanyuma ukande buto iri hano hasi kugira ngo wemeze ko wabibonye.',
    track_rider_heading: 'Umutwara ari mu nzira ajya ku iduka',
    track_realtime: 'Kurikirana umutwara wawe ako kanya',
    track_issue: 'Hari ikibazo ku byo waguze?',
    track_confirm_receipt: 'Emeza ko Wabibonye (Ohereza Ubwishyu)',
    track_dispute_desc: 'Niba hari ibyabuze cyangwa byangiritse, ushobora kugaragaza ikibazo mu masaha 24.',
    track_submit_dispute: 'Garagaza Ikibazo',
    track_dispute_raised: 'Ikibazo cyagaragajwe. Itsinda ryacu ririmo kukireba.',
    track_no_messages: 'Nta butumwa buraboneka. Hamagara umutwara niba ubishaka.',
    track_rider_handover: 'Umutwara ari ku iduka (Guhana ibintu)',
    track_rider_picked_up: 'Umutwara amaze gufata ibyo waguze!',
    track_rider_en_route: 'Umutwara ari mu nzira ajya gufata ibyo waguze.',
    track_rider_verifying: 'Umutwara arimo kureba niba ibyo waguze ari byo ku iduka.',
    track_assigning_rider: 'Turimo gushaka umutwara...',
    track_processing: 'Turimo gutunganya icyo waguze',
    track_packing: 'Umugurisha arimo gupakira ibyo waguze.',
    track_finding_rider: 'Turimo gushaka umutwara uri hafi...',
    track_wait_packing: 'Tegereza gato mu gihe ibyo waguze birimo gupakirwa neza.',
    track_wait_rider: 'Tegereza ko umutwara yakira akazi ko kubigeza.',
    track_delivered: 'Ibyo waguze Byageze!',
    track_placed: 'Ibyo waguze Byatunzwe',
    track_enjoy: 'Isomere ibicuruzwa bishya waguze mu isoko.',
    track_payment_success: 'Ubwishyu bwagenze neza. Tegereza ko umugurisha abyemeza.',
    track_dispute_placeholder: 'Sobanura ikibazo (urugero: Harabura ibiro 2 by\'inyanya)',
    track_dispute_error: 'Andika impamvu ugaragaje ikibazo',
    track_dispute_success: 'Ikibazo cyagaragajwe neza',
    track_dispute_failed: 'Gugaragaza ikibazo byanze',
    payment_released_thanks: 'Murakoze! Ubwishyu bwoherejwe.',
    confirm_receipt_failed: 'Kwemeza ko wabibonye byanze',
    // Notifications
    notif_new: 'Ubutumwa bushya !',
    notif_title: 'Ubutumwa',
    notif_mark_all_read: 'Emeza ko wabusomye bwose',
    notif_empty: 'Nta butumwa ugifite.',
    notif_view_all: 'Reba ibyakozwe byose',
    // Checkout
    checkout_title: 'Kwishyura',
    checkout_delivery_location: '1. Aho uherereye',
    checkout_pinned: 'Yahiswemo',
    checkout_payment_method: '2. Uburyo bwo kwishyura',
    checkout_momo_number: 'Nimero ya Mobile Money',
    checkout_kyc_title: 'Kwemeza umwirondoro (NID irakenewe)',
    checkout_kyc_desc: 'Ibicuruzwa birengeje 50,000 RWF bikeneye nimero y\'indangamuntu.',
    checkout_notes: 'Ibindi bisobanuro ku itangwa ry\'ibicuruzwa',
    checkout_notes_placeholder: 'urugero: Uzane bisi y\'ibihumbi 5, cyangwa unhamagare ugeze ku gipangu cy\'ubururu...',
    checkout_schedule_title: '3. Gahunda yo kugezwaho ibintu',
    checkout_recurring: 'Kora gahunda ihoraho',
    checkout_frequency: 'Inshuro',
    checkout_every_week: 'Buri cyumweru',
    checkout_every_month: 'Buri kwezi',
    checkout_delivery_day: 'Umunsi wo kugezwaho ibintu',
    checkout_schedule_desc: 'Iya mbere izakorwa nonaha. Izikurikira zizajya zikorwa ku munsi wahisemo.',
    checkout_onetime_selected: 'Guhitamo kugezwaho ibintu inshuro imwe gusa.',
    checkout_summary: 'Incamake y\'ibyo waguze',
    checkout_fee: 'Amafaranga yo kugezwaho ibintu',
    checkout_out_of_range: 'Hanze y\'aho dushobora kugeza ibintu (Max 15km)',
    checkout_select_location: 'Hitamo aho uherereye',
    checkout_gateway_fee: 'Amafaranga y\'urubuga (2%)',
    checkout_awaiting_approval: 'Gutegereza kwemeza ubwishyu...',
    checkout_pay_place: 'Ishyura maze utumize',
    checkout_ussd_info: 'Nta murongo wa interineti ufite? Kanda *182# utumize ukoresheje USSD.',
    checkout_moving_forward: 'Ubusabe burimo gukorwa!',
    checkout_cart_empty: 'Agashashi kawe karimo ubusa!',
    checkout_drop_pin: 'Nyamuneka hitamo aho uherereye ku ikarita.',
    checkout_enter_phone: 'Nyamuneka andika nimero yawe ya mobile money.',
    checkout_nid_required: 'Indangamuntu irakenewe ku busabe burengeje 50,000 RWF.',
    checkout_invalid_cart: 'Agashashi gafite ikibazo: amakuru y\'umugurisha ntabonekera.',
    checkout_payment_received: 'Ubwishyu bwabonetse! Ubusabe bwemejwe.',
    checkout_check_phone: 'Nyamuneka reba telefone yawe wemeze ubwishyu.',
    checkout_failed_for: 'Ubusabe bwanze kuri',
    checkout_failed_general: 'Ubusabe bwanze. Nyamuneka ongera ugerageze.',
    // Layout
    lang_en: 'Icyongereza',
    lang_fr: 'Igifaransa',
    lang_kin: 'Ikinyarwanda',
    change_language: 'Hindura Ururimi',
    // Days
    monday: 'Kuwa Mbere',
    tuesday: 'Kuwa Kabiri',
    wednesday: 'Kuwa Gatatu',
    thursday: 'Kuwa Kane',
    friday: 'Kuwa Gatanu',
    saturday: 'Kuwa Gatandatu',
    sunday: 'Ku Cyumweru',
    // Terms & Privacy
    terms_title: 'Amategeko n\'Amabwiriza',
    terms_last_updated: 'Iheruka kuvugururwa: 3 Gicurasi 2026',
    terms_1_title: '1. Kwemera Amategeko',
    terms_1_desc: 'Gukoresha Rwanda Market Facilitator bivuze ko wemeye kubahiriza aya mategeko.',
    terms_2_title: '2. Serivisi Dutanga',
    terms_2_desc: 'Dutanga urubuga ruhuza amasoko yo mu Rwanda n\'abaguzi ndetse n\'abatwara ibintu.',
    terms_3_title: '3. Inshingano z\'Umukoresha',
    terms_3_desc: 'Abakoresha bagomba gutanga amakuru y\'ukuri kandi bakubahiriza amategeko y\'ubucuruzi bwo kuri interineti mu Rwanda.',
    terms_4_title: '4. Kwishyura',
    terms_4_desc: 'Ubwishyu bukorwa binyuze kuri mobile money. Inyungu z\'urubuga zikatwa mu buryo bwikora.',
    privacy_title: 'Ibijyanye n\'Ibanga',
    privacy_last_updated: 'Iheruka kuvugururwa: 3 Gicurasi 2026',
    privacy_intro: 'Ibanga ryawe riraduhengereye cyane. Aya mabwiriza asobanura uko dukusanya n\'uko dukoresha amakuru yawe.',
    privacy_1_title: '1. Gukusanya Amakuru',
    privacy_1_desc: 'Dukusanya amakuru y\'aho uherereye kugira ngo dushobore kugeza ibyo waguze aho uri.',
    privacy_2_title: '2. Ikoreshwa ry\'Amakuru',
    privacy_2_desc: 'Amakuru yawe akoreshwa gusa muri serivisi z\'uru rubuga no kunoza imikorere yarwo.',
    privacy_3_title: '3. Guha Amakuru Abandi',
    privacy_3_desc: 'Duha amakuru yawe abatwara ibintu n\'abishyura gusa kugira ngo ubusabe bwawe bugende neza.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('rmf_language') as Language;
    if (savedLang && (savedLang === 'en' || savedLang === 'fr' || savedLang === 'kin')) {
      setLanguage(savedLang);
    } else {
      const browserLang = typeof window !== 'undefined' ? navigator.language.split('-')[0] : 'en';
      if (browserLang === 'fr') setLanguage('fr');
      else if (browserLang === 'rw') setLanguage('kin');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('rmf_language', lang);
  };

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations['en']];
    if (!translation) {
      return translations['en'][key as keyof typeof translations['en']] || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
